apiVersion: v1
kind: ConfigMap
metadata:
 name: config-autoscaler
 namespace: knative-serving
data:
 container-concurrency-target-default: "2"
 container-concurrency-target-percentage: "100"
 stable-window: "6s"
 max-scale-up-rate: "1000"
 max-scal-down-rate: "1000"
 enable-scale-to-zero: "true"
 scale-to-zero-grace-period: "180s"
 scale-to-zero-pod-retention-period: "0s"
 panic-window-percentage: "10"
 panic-threshold-percentage: "200"
 pod-autoscaler-class: "kpa.autoscaling.knative.dev"
 allow-zero-initial-scale: "true"
