apiVersion: v1
kind: Service
metadata:
  name: macropod-service
spec:
  selector:
    app: macropod
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: macropod-service-account
---
apiVersion: v1
kind: Namespace
metadata:
  name: macropod-functions
  labels:
    name: macropod-functions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macropod-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: macropod-role
subjects:
- kind: ServiceAccount
  name: macropod-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: macropod-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macropod-service
spec:
  selector:
    matchLabels:
      app: macropod
  replicas: 1
  template:
    spec:
      serviceAccountName: macropod-service-account
    metadata:
      labels:
        app: macropod
    spec:
     serviceAccountName: macropod-service-account
     tolerations:
      - key: "master-node"
        value: "master-node"
        effect: "NoSchedule"
     containers:
      - name: macropod-ingress
        image: sysdevtamu/macropod-ingress:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
      - name: macropod-deployer
        image: sysdevtamu/macropod-deployer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
