apiVersion: v1
kind: Service
metadata:
  name: macropod-service
spec:
  selector:
    app: macropod
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: macropod-service-account
---
apiVersion: v1
kind: Namespace
metadata:
  name: macropod
  labels:
    name: macropod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macropod-role
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: macropod-role
subjects:
- kind: ServiceAccount
  name: macropod-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: macropod-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macropod-service
spec:
  selector:
    matchLabels:
      app: macropod
  replicas: 1
  template:
    spec:
      serviceAccountName: macropod-service-account
    metadata:
      labels:
        app: macropod
    spec:
      containers:
      - name: macropod-ingress
        image: arearnest7/macropod-ingress:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_PORT
          value: "8080"
        - name: TTL
          value: "180"
        - name: DEP_CONTROLLER_ADD
          value: "127.0.0.1:8081"
      - name: macropod-deployer
        image: arearnest7/macropod-deployer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SERVICE_PORT
          value: "8081"
        - name: NAMESPACE_INGRESS
          value: "macropod"
        - name: CPU_THRESHOLD_1
          value: "100"
        - name: CPU_THRESHOLD_2
          value: "300"
        - name: MEM_THRESHOLD_1
          value: "100000000"
        - name: MEM_THRESHOLD_2
          value: "10000000000"
        - name: UPDATE_THRESHOLD
          value: "5"
