apiVersion: v1
kind: Service
metadata:
  name: macropod-service
spec:
  selector:
    app: macropod
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: macropod-service-account
---
apiVersion: v1
kind: Namespace
metadata:
  name: macropod
  labels:
    name: macropod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macropod-role
rules:
- apiGroups: ["*"] #adding more permission because deployer is making resources as well 
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: macropod-role
subjects:
- kind: ServiceAccount
  name: macropod-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: macropod-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macropod-service
spec:
  selector:
    matchLabels:
      app: macropod
  replicas: 1
  template:
    metadata:
      labels:
        app: macropod
    spec:
      serviceAccountName: macropod-service-account
      containers:
      - name: macropod-ingress
        image: vasu1711/blue-green:ingress2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_PORT
          value: "8080"
        - name: TTL
          value: "900"
        - name: DEP_CONTROLLER_ADD
          value: "127.0.0.1:8081"
      - name: macropod-deployer
        image: vasu1711/blue-green:deployer1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SERVICE_PORT
          value: "8081"
        - name: NAMESPACE_INGRESS
          value: "macropod"
        - name: CPU_THRESHOLD_1
          value: "100"
        - name: CPU_THRESHOLD_2
          value: "300"
        - name: MEM_THRESHOLD_1
          value: "100000"
        - name: MEM_THRESHOLD_2
          value: "10000000000"
        - name: UPDATE_THRESHOLD
          value: "5"
      - name: prepuller
        image: vasu1711/prepuller:2
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
