apiVersion: v1
kind: Service
metadata:
  name: macropod
spec:
  selector:
    app: macropod
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macropod
spec:
  selector:
    matchLabels:
      app: macropod
  replicas: 1
  template:
    metadata:
      labels:
        app: macropod
    spec:
      containers:
      - name: macropod-ingress
        image: arearnest7/macropod-ingress:latest
        ports:
        - containerPort: 8080
      - name: macropod-deployer
        image: arearnest7/macropod-deployer:latest
        ports:
        - containerPort: 8081
