apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: micro-rpc-a-b
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: micro-rpc-a-b
          image: docker.io/arearnest7/micro-rpc-a-b:latest
          env:
            - name: LEN_A
              value: "10"
            - name: LEN_B
              value: "10"

