apiVersion: v1
kind: Service
metadata:
  name: election-single-pod
spec:
  selector:
    app: election-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-single-pod
spec:
  selector:
    matchLabels:
      app: election-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: election-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: election-gateway
        image: arearnest7/election-gateway:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: ELECTION_GET_RESULTS
            value: redis://127.0.0.1:5001
          - name: ELECTION_VOTE_ENQUEUER
            value: redis://127.0.0.1:5002
          - name: LOGGING_NAME
            value: election-gateway
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: election-get-results
        image: arearnest7/election-get-results:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: LOGGING_NAME
            value: election-get-results
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: election-vote-enqueuer
        image: arearnest7/election-vote-enqueuer:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: ELECTION_VOTE_PROCESSOR
            value: redis://127.0.0.1:5003
          - name: LOGGING_NAME
            value: election-vote-enqueuer
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: election-vote-processor
        image: arearnest7/election-vote-processor:macropod
        ports:
        - containerPort: 5003
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: LOGGING_NAME
            value: election-vote-processor
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
