apiVersion: v1
kind: Service
metadata:
  name: feature-orchestrator
spec:
  selector:
    app: feature-orchestrator
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: feature-extractor
spec:
  selector:
    app: feature-extractor
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: v1
kind: Service
metadata:
  name: feature-wait
spec:
  selector:
    app: feature-wait
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.3
---
apiVersion: v1
kind: Service
metadata:
  name: feature-status
spec:
  selector:
    app: feature-status
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.4
---
apiVersion: v1
kind: Service
metadata:
  name: feature-reducer
spec:
  selector:
    app: feature-reducer
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-orchestrator
spec:
  selector:
    matchLabels:
      app: feature-orchestrator
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-orchestrator
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: feature-orchestrator
        image: arearnest7/feature-orchestrator:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: FEATURE_EXTRACTOR
            value: http://10.43.190.2
          - name: FEATURE_WAIT
            value: http://10.43.190.3
          - name: LOGGING_NAME
            value: feature-orchestrator
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-extractor
spec:
  selector:
    matchLabels:
      app: feature-extractor
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-extractor
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-3
      containers:
      - name: feature-extractor
        image: arearnest7/feature-extractor:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: LOGGING_NAME
            value: feature-extractor
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-wait
spec:
  selector:
    matchLabels:
      app: feature-wait
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-wait
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-4
      containers:
      - name: feature-wait
        image: arearnest7/feature-wait:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: FEATURE_STATUS
            value: http://10.43.190.4
          - name: LOGGING_NAME
            value: feature-wait
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-status
spec:
  selector:
    matchLabels:
      app: feature-status
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-status
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-5
      containers:
      - name: feature-status
        image: arearnest7/feature-status:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: FEATURE_WAIT
            value: http://10.43.190.3
          - name: FEATURE_REDUCER
            value: http://10.43.190.5
          - name: LOGGING_NAME
            value: feature-status
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-reducer
spec:
  selector:
    matchLabels:
      app: feature-reducer
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-reducer
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: feature-reducer
        image: arearnest7/feature-reducer:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: LOGGING_NAME
            value: feature-reducer
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
