apiVersion: v1
kind: Service
metadata:
  name: feature-single-pod
spec:
  selector:
    app: feature-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-single-pod
spec:
  selector:
    matchLabels:
      app: feature-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: feature-orchestrator
        image: arearnest7/feature-orchestrator:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: FEATURE_EXTRACTOR
            value: 127.0.0.1:5001
          - name: FEATURE_WAIT
            value: 127.0.0.1:5002
      - name: feature-extractor
        image: arearnest7/feature-extractor:macropod
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: APP_PV
            value: "/macropod-pv"
      - name: feature-wait
        image: arearnest7/feature-wait:macropod
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: FEATURE_STATUS
            value: 127.0.0.1:5003
      - name: feature-status
        image: arearnest7/feature-status:macropod
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: FEATURE_WAIT
            value: 127.0.0.1:5002
          - name: FEATURE_REDUCER
            value: 127.0.0.1:5004
      - name: feature-reducer
        image: arearnest7/feature-reducer:macropod
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
          - name: APP_PV
            value: "/macropod-pv"
