apiVersion: v1
kind: Service
metadata:
  name: feature-single-pod
spec:
  selector:
    app: feature-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-single-pod
spec:
  selector:
    matchLabels:
      app: feature-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: feature-orchestrator
        image: arearnest7/feature-orchestrator:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: FEATURE_EXTRACTOR
          - name: FEATURE_WAIT
      - name: feature-extractor
        image: arearnest7/feature-extractor:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
      - name: feature-wait
        image: arearnest7/feature-wait:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: FEATURE_STATUS
      - name: feature-status
        image: arearnest7/feature-status:macropod
        ports:
        - containerPort: 5003
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: FEATURE_WAIT
          - name: FEATURE_REDUCER
      - name: feature-reducer
        image: arearnest7/feature-reducer:macropod
        ports:
        - containerPort: 5004
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
