apiVersion: v1
kind: Service
metadata:
  name: feature-single-oci
spec:
  selector:
    app: feature-single-oci
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-single-oci
spec:
  selector:
    matchLabels:
      app: feature-single-oci
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-single-oci
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: feature-orchestrator
        image: arearnest7/feature-orchestrator:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: FEATURE_EXTRACTOR
            value: 127.0.0.1:5001
          - name: FEATURE_WAIT
            value: 127.0.0.1:5002
          - name: LOGGING_NAME
            value: feature-orchestrator
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: feature-extractor
        image: arearnest7/feature-extractor:oci
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: LOGGING_NAME
            value: feature-extractor
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: feature-wait
        image: arearnest7/feature-wait:oci
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: FEATURE_STATUS
            value: 127.0.0.1:5003
          - name: LOGGING_NAME
            value: feature-wait
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: feature-status
        image: arearnest7/feature-status:oci
        ports:
        - containerPort: 5003
        env:
          - name: PORT
            value: "5003"
          - name: FEATURE_WAIT
            value: 127.0.0.1:5002
          - name: FEATURE_REDUCER
            value: 127.0.0.1:5004
          - name: LOGGING_NAME
            value: feature-status
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: feature-reducer
        image: arearnest7/feature-reducer:oci
        ports:
        - containerPort: 5004
        env:
          - name: PORT
            value: "5004"
          - name: LOGGING_NAME
            value: feature-reducer
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
