apiVersion: v1
kind: Service
metadata:
  name: hotel-single-pod
spec:
  selector:
    app: hotel-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-single-pod
spec:
  selector:
    matchLabels:
      app: hotel-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: hotel-frontend
        image: arearnest7/hotel-frontend:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: HOTEL_SEARCH
            value: redis://127.0.0.1:5001
          - name: HOTEL_RECOMMEND
            value: redis://127.0.0.1:5002
          - name: HOTEL_RESERVE
            value: redis://127.0.0.1:5003
          - name: HOTEL_USER
            value: redis://127.0.0.1:5004
          - name: LOGGING_NAME
            value: hotel-frontend
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: hotel-search
        image: arearnest7/hotel-search:macropod
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: HOTEL_GEO
            value: redis://127.0.0.1:5005
          - name: HOTEL_RATE
            value: redis://127.0.0.1:5007
          - name: LOGGING_NAME
            value: hotel-search
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: hotel-recommend
        image: arearnest7/hotel-recommend:macropod
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: hotel-recommend
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: hotel-reserve
        image: arearnest7/hotel-reserve:macropod
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: hotel-reserve
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: hotel-user
        image: arearnest7/hotel-user:macropod
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: hotel-user
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: hotel-geo
        image: arearnest7/hotel-geo:macropod
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: hotel-geo
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: hotel-profile
        image: arearnest7/hotel-profile:macropod
        ports:
        - containerPort: 5006
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5006"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: hotel-profile
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: hotel-rate
        image: arearnest7/hotel-rate:macropod
        ports:
        - containerPort: 5007
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5007"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: hotel-rate
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
