apiVersion: v1
kind: Service
metadata:
  name: pipelined-single-pod
spec:
  selector:
    app: pipelined-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-single-pod
spec:
  selector:
    matchLabels:
      app: pipelined-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: pipelined-main
        image: arearnest7/pipelined-main:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: PIPELINED_MAIN
          - name: PIPELINED_CHECKSUM
          - name: PIPELINED_ZIP
          - name: PIPELINED_ENCRYPT
      - name: pipelined-checksum
        image: arearnest7/pipelined-checksum:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
      - name: pipelined-zip
        image: arearnest7/pipelined-zip:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
      - name: pipelined-encrypt
        image: arearnest7/pipelined-encrypt:macropod
        ports:
        - containerPort: 5003
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
