apiVersion: v1
kind: Service
metadata:
  name: pipelined-main
spec:
  selector:
    app: pipelined-main
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-checksum
spec:
  selector:
    app: pipelined-checksum
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-zip
spec:
  selector:
    app: pipelined-zip
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.3
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-encrypt
spec:
  selector:
    app: pipelined-encrypt
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-main
spec:
  selector:
    matchLabels:
      app: pipelined-main
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-main
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: pipelined-main
        image: arearnest7/pipelined-main:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: PIPELINED_MAIN
            value: http://10.43.190.1
          - name: PIPELINED_CHECKSUM
            value: http://10.43.190.2
          - name: PIPELINED_ZIP
            value: http://10.43.190.3
          - name: PIPELINED_ENCRYPT
            value: http://10.43.190.4
          - name: LOGGING_NAME
            value: pipelined-main
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-checksum
spec:
  selector:
    matchLabels:
      app: pipelined-checksum
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-checksum
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-3
      containers:
      - name: pipelined-checksum
        image: arearnest7/pipelined-checksum:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: LOGGING_NAME
            value: pipelined-checksum
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-zip
spec:
  selector:
    matchLabels:
      app: pipelined-zip
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-zip
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-4
      containers:
      - name: pipelined-zip
        image: arearnest7/pipelined-zip:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: LOGGING_NAME
            value: pipelined-zip
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-encrypt
spec:
  selector:
    matchLabels:
      app: pipelined-encrypt
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-encrypt
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-5
      containers:
      - name: pipelined-encrypt
        image: arearnest7/pipelined-encrypt:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: LOGGING_NAME
            value: pipelined-encrypt
          - name: LOGGING_IP
            value: 127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
