apiVersion: v1
kind: Service
metadata:
  name: pipelined-main
spec:
  selector:
    app: pipelined-main
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-checksum
spec:
  selector:
    app: pipelined-checksum
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-zip
spec:
  selector:
    app: pipelined-zip
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.3
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-encrypt
spec:
  selector:
    app: pipelined-encrypt
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-main
spec:
  selector:
    matchLabels:
      app: pipelined-main
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-main
    spec:
      containers:
      - name: pipelined-main
        image: arearnest7/pipelined-main:faastroute
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: PIPELINED_CHECKSUM
            value: http://10.43.190.2
          - name: PIPELINED_ZIP
            value: http://10.43.190.3
          - name: PIPELINED_ENCRYPT
            value: http://10.43.190.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-checksum
spec:
  selector:
    matchLabels:
      app: pipelined-checksum
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-checksum
    spec:
      containers:
      - name: pipelined-checksum
        image: arearnest7/pipelined-checksum:faastroute
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-zip
spec:
  selector:
    matchLabels:
      app: pipelined-zip
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-zip
    spec:
      containers:
      - name: pipelined-zip
        image: arearnest7/pipelined-zip:faastroute
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-encrypt
spec:
  selector:
    matchLabels:
      app: pipelined-encrypt
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-encrypt
    spec:
      containers:
      - name: pipelined-encrypt
        image: arearnest7/pipelined-encrypt:faastroute
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
