apiVersion: v1
kind: Service
metadata:
  name: sentiment-single-pod
spec:
  selector:
    app: sentiment-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-single-pod
spec:
  selector:
    matchLabels:
      app: sentiment-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: sentiment-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: sentiment-main
        image: arearnest7/sentiment-main:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: SENTIMENT_READ_CSV
            value: redis://127.0.0.1:5001
          - name: LOGGING_NAME
            value: sentiment-main
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-read-csv
        image: arearnest7/sentiment-read-csv:macropod
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: SENTIMENT_PRODUCT_OR_SERVICE
            value: redis://127.0.0.1:5002
          - name: LOGGING_NAME
            value: sentiment-read-csv
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-product-or-service
        image: arearnest7/sentiment-product-or-service:macropod
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: SENTIMENT_CFAIL
            value: redis://127.0.0.1:5003
          - name: SENTIMENT_PRODUCT_SENTIMENT
            value: redis://127.0.0.1:5004
          - name: SENTIMENT_SERVICE_SENTIMENT
            value: redis://127.0.0.1:5009
          - name: LOGGING_NAME
            value: sentiment-product-or-service
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-cfail
        image: arearnest7/sentiment-cfail:macropod
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: sentiment-cfail
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-product-sentiment
        image: arearnest7/sentiment-product-sentiment:macropod
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: SENTIMENT_PRODUCT_RESULT
            value: redis://127.0.0.1:5005
          - name: LOGGING_NAME
            value: sentiment-product-sentiment
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-product-result
        image: arearnest7/sentiment-product-result:macropod
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: SENTIMENT_SFAIL
            value: redis://127.0.0.1:5006
          - name: SENTIMENT_SNS
            value: redis://127.0.0.1:5007
          - name: SENTIMENT_DB
            value: redis://127.0.0.1:5008
          - name: LOGGING_NAME
            value: sentiment-product-result
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-sfail
        image: arearnest7/sentiment-sfail:macropod
        ports:
        - containerPort: 5006
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5006"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: sentiment-sfail
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-sns
        image: arearnest7/sentiment-sns:macropod
        ports:
        - containerPort: 5007
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5007"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: SENTIMENT_DB
            value: redis://127.0.0.1:5008
          - name: LOGGING_NAME
            value: sentiment-sns
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-db
        image: arearnest7/sentiment-db:macropod
        ports:
        - containerPort: 5008
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5008"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LOGGING_NAME
            value: sentiment-db
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-service-sentiment
        image: arearnest7/sentiment-service-sentiment:macropod
        ports:
        - containerPort: 5009
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5009"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: SENTIMENT_SERVICE_RESULT
            value: redis://127.0.0.1:5010
          - name: LOGGING_NAME
            value: sentiment-service-sentiment
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: sentiment-service-result
        image: arearnest7/sentiment-service-result:macropod
        ports:
        - containerPort: 5010
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5010"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: SENTIMENT_SFAIL
            value: redis://127.0.0.1:5006
          - name: SENTIMENT_SNS
            value: redis://127.0.0.1:5007
          - name: SENTIMENT_DB
            value: redis://127.0.0.1:5008
          - name: LOGGING_NAME
            value: sentiment-service-result
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
