apiVersion: v1
kind: Service
metadata:
  name: sentiment-single-pod
spec:
  selector:
    app: sentiment-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-single-pod
spec:
  selector:
    matchLabels:
      app: sentiment-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: sentiment-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: sentiment-main
        image: arearnest7/sentiment-main:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: SENTIMENT_READ_CSV
      - name: sentiment-read-csv
        image: arearnest7/sentiment-read-csv:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: SENTIMENT_PRODUCT_OR_SERVICE
      - name: sentiment-product-or-service
        image: arearnest7/sentiment-product-or-service:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: SENTIMENT_CFAIL
          - name: SENTIMENT_PRODUCT_SENTIMENT
          - name: SENTIMENT_SERVICE_SENTIMENT
      - name: sentiment-cfail
        image: arearnest7/sentiment-cfail:macropod
        ports:
        - containerPort: 5003
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
      - name: sentiment-product-sentiment
        image: arearnest7/sentiment-product-sentiment:macropod
        ports:
        - containerPort: 5004
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
          - name: SENTIMENT_PRODUCT_RESULT
      - name: sentiment-product-result
        image: arearnest7/sentiment-product-result:macropod
        ports:
        - containerPort: 5005
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
          - name: SENTIMENT_SFAIL
          - name: SENTIMENT_SNS
          - name: SENTIMENT_DB
      - name: sentiment-sfail
        image: arearnest7/sentiment-sfail:macropod
        ports:
        - containerPort: 5006
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5006"
      - name: sentiment-sns
        image: arearnest7/sentiment-sns:macropod
        ports:
        - containerPort: 5007
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5007"
          - name: SENTIMENT_DB
      - name: sentiment-db
        image: arearnest7/sentiment-db:macropod
        ports:
        - containerPort: 5008
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5008"
      - name: sentiment-service-sentiment
        image: arearnest7/sentiment-service-sentiment:macropod
        ports:
        - containerPort: 5009
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5009"
          - name: SENTIMENT_SERVICE_RESULT
      - name: sentiment-service-result
        image: arearnest7/sentiment-service-result:macropod
        ports:
        - containerPort: 5010
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5010"
          - name: SENTIMENT_SFAIL
          - name: SENTIMENT_SNS
          - name: SENTIMENT_DB
