apiVersion: v1
kind: Service
metadata:
  name: video-single-mmap
spec:
  selector:
    app: video-single-mmap
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-single-mmap
spec:
  selector:
    matchLabels:
      app: video-single-mmap
  replicas: 1
  template:
    metadata:
      labels:
        app: video-single-mmap
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: video-streaming
        image: arearnest7/video-streaming:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: VIDEO_DECODER
            value: 127.0.0.1:5001
      - name: video-decoder
        image: arearnest7/video-decoder:macropod
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: VIDEO_RECOG
            value: 127.0.0.1:5002
      - name: video-recog
        image: arearnest7/video-recog:macropod
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: APP_PV
            value: "/macropod-pv"
