apiVersion: v1
kind: Service
metadata:
  name: video-single-pod
spec:
  selector:
    app: video-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-single-pod
spec:
  selector:
    matchLabels:
      app: video-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: video-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      volumes:
      - name: faastroute-pv
        emptyDir:
          medium: Memory
      containers:
      - name: video-streaming
        image: arearnest7/video-streaming:faastroute
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: faastroute-pv
          mountPath: /faastroute-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: RPC_PV
            value: "/faastroute-pv"
          - name: RPC_DEST_PV
            value: "/faastroute-pv"
          - name: VIDEO_DECODER
            value: http://localhost:5001
      - name: video-decoder
        image: arearnest7/video-decoder:faastroute
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: faastroute-pv
          mountPath: /faastroute-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: RPC_PV
            value: "/faastroute-pv"
          - name: RPC_DEST_PV
            value: "/faastroute-pv"
          - name: APP_PV
            value: "/faastroute-pv"
          - name: VIDEO_RECOG
            value: http://localhost:5002
      - name: video-recog
        image: arearnest7/video-recog:faastroute
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: faastroute-pv
          mountPath: /faastroute-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: APP_PV
            value: "/faastroute-pv"
