apiVersion: v1
kind: Service
metadata:
  name: video-single-pod
spec:
  selector:
    app: video-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-single-pod
spec:
  selector:
    matchLabels:
      app: video-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: video-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: video-streaming
        image: arearnest7/video-streaming:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: VIDEO_DECODER
            value: redis://127.0.0.1:5001
          - name: LOGGING_NAME
            value: video-streaming
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: video-decoder
        image: arearnest7/video-decoder:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: VIDEO_RECOG
            value: redis://127.0.0.1:5002
          - name: LOGGING_NAME
            value: video-decoder
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: video-recog
        image: arearnest7/video-recog:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: LOGGING_NAME
            value: video-recog
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
