apiVersion: v1
kind: Service
metadata:
  name: wage-single-pod
spec:
  selector:
    app: wage-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wage-single-pod
spec:
  selector:
    matchLabels:
      app: wage-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: wage-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      containers:
      - name: wage-validator
        image: arearnest7/wage-validator:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: WAGE_FORMAT
            value: redis://127.0.0.1:5001
          - name: LOGGING_NAME
            value: wage-validator
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: wage-format
        image: arearnest7/wage-format:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: WAGE_WRITE_RAW
            value: redis://127.0.0.1:5002
          - name: LOGGING_NAME
            value: wage-format
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: wage-write-raw
        image: arearnest7/wage-write-raw:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: WAGE_STATS
            value: redis://127.0.0.1:5003
          - name: LOGGING_NAME
            value: wage-write-raw
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: wage-stats
        image: arearnest7/wage-stats:macropod
        ports:
        - containerPort: 5003
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: WAGE_AVG
            value: redis://127.0.0.1:5004
          - name: LOGGING_NAME
            value: wage-stats
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: wage-avg
        image: arearnest7/wage-avg:macropod
        ports:
        - containerPort: 5004
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
          - name: WAGE_SUM
            value: redis://127.0.0.1:5005
          - name: LOGGING_NAME
            value: wage-avg
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: wage-sum
        image: arearnest7/wage-sum:macropod
        ports:
        - containerPort: 5005
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
          - name: WAGE_MERIT
            value: redis://127.0.0.1:5006
          - name: LOGGING_NAME
            value: wage-sum
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: wage-merit
        image: arearnest7/wage-merit:macropod
        ports:
        - containerPort: 5006
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5006"
          - name: WAGE_WRITE_MERIT
            value: redis://127.0.0.1:5007
          - name: LOGGING_NAME
            value: wage-merit
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: wage-write-merit
        image: arearnest7/wage-write-merit:macropod
        ports:
        - containerPort: 5007
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5007"
          - name: LOGGING_NAME
            value: wage-write-merit
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
