apiVersion: v1
kind: Service
metadata:
  name: wage-single-pod
spec:
  selector:
    app: wage-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wage-single-pod
spec:
  selector:
    matchLabels:
      app: wage-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: wage-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: wage-validator
        image: arearnest7/wage-validator:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: WAGE_FORMAT
            value: http://localhost:5001
      - name: wage-format
        image: arearnest7/wage-format:macropod
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: WAGE_WRITE_RAW
            value: http://localhost:5002
      - name: wage-write-raw
        image: arearnest7/wage-write-raw:macropod
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: WAGE_STATS
            value: http://localhost:5003
      - name: wage-stats
        image: arearnest7/wage-stats:macropod
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: WAGE_AVG
            value: http://localhost:5004
      - name: wage-avg
        image: arearnest7/wage-avg:macropod
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: WAGE_SUM
            value: http://localhost:5005
      - name: wage-sum
        image: arearnest7/wage-sum:macropod
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: WAGE_MERIT
            value: http://localhost:5006
      - name: wage-merit
        image: arearnest7/wage-merit:macropod
        ports:
        - containerPort: 5006
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5006"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: WAGE_WRITE_MERIT
            value: http://localhost:5007
      - name: wage-write-merit
        image: arearnest7/wage-write-merit:macropod
        ports:
        - containerPort: 5007
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5007"
          - name: APP_PV
            value: "/macropod-pv"
