# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wf.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08wf.proto\x12\x08\x66unction\"\xaa\x01\n\x0bRequestBody\x12\x11\n\x04\x64\x61ta\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x19\n\x0crequest_type\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07pv_path\x18\x06 \x01(\tH\x02\x88\x01\x01\x42\x07\n\x05_dataB\x0f\n\r_request_typeB\n\n\x08_pv_path\"\\\n\x0cResponseBody\x12\x12\n\x05reply\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x14\n\x07pv_path\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_replyB\n\n\x08_pv_path2T\n\x0cgRPCFunction\x12\x44\n\x13gRPCFunctionHandler\x12\x15.function.RequestBody\x1a\x16.function.ResponseBodyB\tZ\x07./wf_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./wf_pb'
  _globals['_REQUESTBODY']._serialized_start=23
  _globals['_REQUESTBODY']._serialized_end=193
  _globals['_RESPONSEBODY']._serialized_start=195
  _globals['_RESPONSEBODY']._serialized_end=287
  _globals['_GRPCFUNCTION']._serialized_start=289
  _globals['_GRPCFUNCTION']._serialized_end=373
# @@protoc_insertion_point(module_scope)
