apiVersion: v1
kind: Service
metadata:
  name: election-pod
spec:
  selector:
    app: election-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-pod
spec:
  selector:
    matchLabels:
      app: election-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: election-pod
    spec:
      containers:
      - name: election-gateway
        image: arearnest7/election-gateway-oci:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: ELECTION_GET_RESULTS
            value: http://localhost:5001
          - name: ELECTION_VOTE_ENQUEUER
            value: http://localhost:5002
      - name: election-get-results
        image: arearnest7/election-get-results-oci:latest
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
      - name: election-vote-enqueuer
        image: arearnest7/election-vote-enqueuer-oci:latest
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: ELECTION_VOTE_PROCESSOR
            value: http://localhost:5003
      - name: election-vote-processor
        image: arearnest7/election-vote-processor-oci:latest
        ports:
        - containerPort: 5003
        env:
          - name: PORT
            value: "5003"
