apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-05-05T22:49:32Z"
  generation: 1
  name: video-analytics-0
  namespace: video-analytics-0
  resourceVersion: "20776"
  uid: a32f1be2-5865-4f0f-9344-3366548c5159
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: video-analytics-0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: video-analytics-0
    spec:
      containers:
      - env:
        - name: SERVICE_TYPE
          value: HTTP
        - name: GRPC_THREAD
          value: "10"
        - name: FUNC_PORT
          value: "5000"
        - name: RPC_PV
          value: /macropod-pv
        - name: RPC_DEST_PV
          value: /macropod-pv
        - name: LOGGING_NAME
          value: video-streaming
        - name: LOGGING_URL
          value: redis://127.0.0.1
        - name: LOGGING_PASSWORD
          value: password
        - name: VIDEO_DECODER
          value: redis://127.0.0.1:5001
        image: arearnest7/video-streaming:macropod
        imagePullPolicy: Always
        name: video-streaming
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /macropod-pv
          name: macropod-pv
      - env:
        - name: SERVICE_TYPE
          value: GRPC
        - name: GRPC_THREAD
          value: "10"
        - name: FUNC_PORT
          value: "5002"
        - name: APP_PV
          value: /macropod-pv
        - name: LOGGING_NAME
          value: video-recog
        - name: LOGGING_URL
          value: redis://127.0.0.1
        - name: URL
          value: 'http://127.0.0.1:'
        - name: LOGGING_PASSWORD
          value: password
        image: arearnest7/video-recog:macropod
        imagePullPolicy: Always
        name: video-recog
        ports:
        - containerPort: 5002
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /macropod-pv
          name: macropod-pv
      - env:
        - name: SERVICE_TYPE
          value: GRPC
        - name: GRPC_THREAD
          value: "10"
        - name: FUNC_PORT
          value: "5001"
        - name: RPC_PV
          value: /macropod-pv
        - name: RPC_DEST_PV
          value: /macropod-pv
        - name: LOGGING_NAME
          value: video-decoder
        - name: APP_PV
          value: /macropod-pv
        - name: LOGGING_URL
          value: redis://127.0.0.1
        - name: LOGGING_PASSWORD
          value: password
        - name: VIDEO_RECOG
          value: redis://127.0.0.1:5002
        image: arearnest7/video-decoder:macropod
        imagePullPolicy: Always
        name: video-decoder
        ports:
        - containerPort: 5001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /macropod-pv
          name: macropod-pv
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: k3d-mycluster-agent-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: macropod-pv
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-05T22:49:35Z"
    lastUpdateTime: "2024-05-05T22:49:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-05T22:49:32Z"
    lastUpdateTime: "2024-05-05T22:49:35Z"
    message: ReplicaSet "video-analytics-0-6ff669b5bb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
