


apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test
  namespace: nginx-test2
  labels: 
    "cpu_threshold_1": "1"
    "cpu_threshold_2" : "2"
    "mm_threshold_1" : "1"
    "mm_threshold_2" : "1"
data:
  my-config.json: |
    [
      {
        "name": "decoder",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "nginx:latest",
          "pullPolicy": "Always"
        },
        "env": {
          "name": "test",
          "value": "test-value"
        },
        "service": {
          "type": "ClusterIP",
          "port": 80,
          "targetPort": 80
        },
        "ingress": {
          "host": "b.example.com"
        }
      },
      {
        "name": "recog",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "nginx:latest",
          "pullPolicy": "Always"
        },
        "env": {
          "name": "test",
          "value": "test-value"
        },
        "service": {
          "type": "ClusterIP",
          "port": 80,
          "targetPort": 80
        },
        "ingress": {
          "host": "b.example.com"
        }
      }
    ]


---





apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test
  namespace: nginx-test1
  labels: 
    "cpu_threshold_1": "1"
    "cpu_threshold_2" : "2"
    "mm_threshold_1" : "1"
    "mm_threshold_2" : "1"
data:
  my-config.json: |
    [
      {
        "name": "decoder",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "nginx:latest",
          "pullPolicy": "Always"
        },
        "env": {
          "name": "test",
          "value": "test-value"
        },
        "service": {
          "type": "ClusterIP",
          "port": 80,
          "targetPort": 80
        },
        "ingress": {
          "host": "b.example.com"
        }
      }
    ]




---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test
  namespace: nginx-test0
  labels: 
    "cpu_threshold_1": "1"
    "cpu_threshold_2" : "2"
    "mm_threshold_1" : "1"
    "mm_threshold_2" : "1"
data:
  my-config.json: |
    [
      {
        "name": "decoder",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "nginx:latest",
          "pullPolicy": "Always"
        },
        "env": {
          "name": "test",
          "value": "test-value"
        },
        "service": {
          "type": "ClusterIP",
          "port": 80,
          "targetPort": 80
        },
        "ingress": {
          "host": "b.example.com"
        }
      },
    ]


