// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: macropod.proto

package macropod_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MacroPodFunction_Invoke_FullMethodName = "/macropod.MacroPodFunction/Invoke"
)

// MacroPodFunctionClient is the client API for MacroPodFunction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MacroPodFunctionClient interface {
	Invoke(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
}

type macroPodFunctionClient struct {
	cc grpc.ClientConnInterface
}

func NewMacroPodFunctionClient(cc grpc.ClientConnInterface) MacroPodFunctionClient {
	return &macroPodFunctionClient{cc}
}

func (c *macroPodFunctionClient) Invoke(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodFunction_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MacroPodFunctionServer is the server API for MacroPodFunction service.
// All implementations must embed UnimplementedMacroPodFunctionServer
// for forward compatibility.
type MacroPodFunctionServer interface {
	Invoke(context.Context, *FunctionRequest) (*MacroPodReply, error)
	mustEmbedUnimplementedMacroPodFunctionServer()
}

// UnimplementedMacroPodFunctionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMacroPodFunctionServer struct{}

func (UnimplementedMacroPodFunctionServer) Invoke(context.Context, *FunctionRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedMacroPodFunctionServer) mustEmbedUnimplementedMacroPodFunctionServer() {}
func (UnimplementedMacroPodFunctionServer) testEmbeddedByValue()                          {}

// UnsafeMacroPodFunctionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MacroPodFunctionServer will
// result in compilation errors.
type UnsafeMacroPodFunctionServer interface {
	mustEmbedUnimplementedMacroPodFunctionServer()
}

func RegisterMacroPodFunctionServer(s grpc.ServiceRegistrar, srv MacroPodFunctionServer) {
	// If the following call pancis, it indicates UnimplementedMacroPodFunctionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MacroPodFunction_ServiceDesc, srv)
}

func _MacroPodFunction_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodFunctionServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodFunction_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodFunctionServer).Invoke(ctx, req.(*FunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MacroPodFunction_ServiceDesc is the grpc.ServiceDesc for MacroPodFunction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MacroPodFunction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "macropod.MacroPodFunction",
	HandlerType: (*MacroPodFunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _MacroPodFunction_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "macropod.proto",
}

const (
	MacroPodDeployer_Deployment_FullMethodName        = "/macropod.MacroPodDeployer/Deployment"
	MacroPodDeployer_Config_FullMethodName            = "/macropod.MacroPodDeployer/Config"
	MacroPodDeployer_CreateWorkflow_FullMethodName    = "/macropod.MacroPodDeployer/CreateWorkflow"
	MacroPodDeployer_UpdateWorkflow_FullMethodName    = "/macropod.MacroPodDeployer/UpdateWorkflow"
	MacroPodDeployer_DeleteWorkflow_FullMethodName    = "/macropod.MacroPodDeployer/DeleteWorkflow"
	MacroPodDeployer_UpdateDeployments_FullMethodName = "/macropod.MacroPodDeployer/UpdateDeployments"
	MacroPodDeployer_CreateDeployment_FullMethodName  = "/macropod.MacroPodDeployer/CreateDeployment"
	MacroPodDeployer_TTLDelete_FullMethodName         = "/macropod.MacroPodDeployer/TTLDelete"
	MacroPodDeployer_UpdateManifest_FullMethodName    = "/macropod.MacroPodDeployer/UpdateManifest"
)

// MacroPodDeployerClient is the client API for MacroPodDeployer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MacroPodDeployerClient interface {
	Deployment(ctx context.Context, in *DeploymentServiceRequest, opts ...grpc.CallOption) (*DeploymentServiceReply, error)
	Config(ctx context.Context, in *ConfigStruct, opts ...grpc.CallOption) (*MacroPodReply, error)
	CreateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error)
	UpdateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error)
	DeleteWorkflow(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	UpdateDeployments(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	CreateDeployment(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	TTLDelete(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	UpdateManifest(ctx context.Context, in *MacroPodManifest, opts ...grpc.CallOption) (*MacroPodManifest, error)
}

type macroPodDeployerClient struct {
	cc grpc.ClientConnInterface
}

func NewMacroPodDeployerClient(cc grpc.ClientConnInterface) MacroPodDeployerClient {
	return &macroPodDeployerClient{cc}
}

func (c *macroPodDeployerClient) Deployment(ctx context.Context, in *DeploymentServiceRequest, opts ...grpc.CallOption) (*DeploymentServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentServiceReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_Deployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) Config(ctx context.Context, in *ConfigStruct, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) CreateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) UpdateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_UpdateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) DeleteWorkflow(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_DeleteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) UpdateDeployments(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_UpdateDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) CreateDeployment(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_CreateDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) TTLDelete(ctx context.Context, in *DeployerRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodDeployer_TTLDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodDeployerClient) UpdateManifest(ctx context.Context, in *MacroPodManifest, opts ...grpc.CallOption) (*MacroPodManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodManifest)
	err := c.cc.Invoke(ctx, MacroPodDeployer_UpdateManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MacroPodDeployerServer is the server API for MacroPodDeployer service.
// All implementations must embed UnimplementedMacroPodDeployerServer
// for forward compatibility.
type MacroPodDeployerServer interface {
	Deployment(context.Context, *DeploymentServiceRequest) (*DeploymentServiceReply, error)
	Config(context.Context, *ConfigStruct) (*MacroPodReply, error)
	CreateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error)
	UpdateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error)
	DeleteWorkflow(context.Context, *DeployerRequest) (*MacroPodReply, error)
	UpdateDeployments(context.Context, *DeployerRequest) (*MacroPodReply, error)
	CreateDeployment(context.Context, *DeployerRequest) (*MacroPodReply, error)
	TTLDelete(context.Context, *DeployerRequest) (*MacroPodReply, error)
	UpdateManifest(context.Context, *MacroPodManifest) (*MacroPodManifest, error)
	mustEmbedUnimplementedMacroPodDeployerServer()
}

// UnimplementedMacroPodDeployerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMacroPodDeployerServer struct{}

func (UnimplementedMacroPodDeployerServer) Deployment(context.Context, *DeploymentServiceRequest) (*DeploymentServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deployment not implemented")
}
func (UnimplementedMacroPodDeployerServer) Config(context.Context, *ConfigStruct) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedMacroPodDeployerServer) CreateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedMacroPodDeployerServer) UpdateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkflow not implemented")
}
func (UnimplementedMacroPodDeployerServer) DeleteWorkflow(context.Context, *DeployerRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkflow not implemented")
}
func (UnimplementedMacroPodDeployerServer) UpdateDeployments(context.Context, *DeployerRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeployments not implemented")
}
func (UnimplementedMacroPodDeployerServer) CreateDeployment(context.Context, *DeployerRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeployment not implemented")
}
func (UnimplementedMacroPodDeployerServer) TTLDelete(context.Context, *DeployerRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TTLDelete not implemented")
}
func (UnimplementedMacroPodDeployerServer) UpdateManifest(context.Context, *MacroPodManifest) (*MacroPodManifest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateManifest not implemented")
}
func (UnimplementedMacroPodDeployerServer) mustEmbedUnimplementedMacroPodDeployerServer() {}
func (UnimplementedMacroPodDeployerServer) testEmbeddedByValue()                          {}

// UnsafeMacroPodDeployerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MacroPodDeployerServer will
// result in compilation errors.
type UnsafeMacroPodDeployerServer interface {
	mustEmbedUnimplementedMacroPodDeployerServer()
}

func RegisterMacroPodDeployerServer(s grpc.ServiceRegistrar, srv MacroPodDeployerServer) {
	// If the following call pancis, it indicates UnimplementedMacroPodDeployerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MacroPodDeployer_ServiceDesc, srv)
}

func _MacroPodDeployer_Deployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).Deployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_Deployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).Deployment(ctx, req.(*DeploymentServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).Config(ctx, req.(*ConfigStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).CreateWorkflow(ctx, req.(*WorkflowStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_UpdateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).UpdateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_UpdateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).UpdateWorkflow(ctx, req.(*WorkflowStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_DeleteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).DeleteWorkflow(ctx, req.(*DeployerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_UpdateDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).UpdateDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_UpdateDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).UpdateDeployments(ctx, req.(*DeployerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_CreateDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).CreateDeployment(ctx, req.(*DeployerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_TTLDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).TTLDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_TTLDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).TTLDelete(ctx, req.(*DeployerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodDeployer_UpdateManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MacroPodManifest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodDeployerServer).UpdateManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodDeployer_UpdateManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodDeployerServer).UpdateManifest(ctx, req.(*MacroPodManifest))
	}
	return interceptor(ctx, in, info, handler)
}

// MacroPodDeployer_ServiceDesc is the grpc.ServiceDesc for MacroPodDeployer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MacroPodDeployer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "macropod.MacroPodDeployer",
	HandlerType: (*MacroPodDeployerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deployment",
			Handler:    _MacroPodDeployer_Deployment_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _MacroPodDeployer_Config_Handler,
		},
		{
			MethodName: "CreateWorkflow",
			Handler:    _MacroPodDeployer_CreateWorkflow_Handler,
		},
		{
			MethodName: "UpdateWorkflow",
			Handler:    _MacroPodDeployer_UpdateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _MacroPodDeployer_DeleteWorkflow_Handler,
		},
		{
			MethodName: "UpdateDeployments",
			Handler:    _MacroPodDeployer_UpdateDeployments_Handler,
		},
		{
			MethodName: "CreateDeployment",
			Handler:    _MacroPodDeployer_CreateDeployment_Handler,
		},
		{
			MethodName: "TTLDelete",
			Handler:    _MacroPodDeployer_TTLDelete_Handler,
		},
		{
			MethodName: "UpdateManifest",
			Handler:    _MacroPodDeployer_UpdateManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "macropod.proto",
}

const (
	MacroPodIngress_Config_FullMethodName         = "/macropod.MacroPodIngress/Config"
	MacroPodIngress_WorkflowInvoke_FullMethodName = "/macropod.MacroPodIngress/WorkflowInvoke"
	MacroPodIngress_FunctionInvoke_FullMethodName = "/macropod.MacroPodIngress/FunctionInvoke"
	MacroPodIngress_CreateWorkflow_FullMethodName = "/macropod.MacroPodIngress/CreateWorkflow"
	MacroPodIngress_UpdateWorkflow_FullMethodName = "/macropod.MacroPodIngress/UpdateWorkflow"
	MacroPodIngress_DeleteWorkflow_FullMethodName = "/macropod.MacroPodIngress/DeleteWorkflow"
	MacroPodIngress_Eval_FullMethodName           = "/macropod.MacroPodIngress/Eval"
	MacroPodIngress_EvalMetrics_FullMethodName    = "/macropod.MacroPodIngress/EvalMetrics"
	MacroPodIngress_EvalLatency_FullMethodName    = "/macropod.MacroPodIngress/EvalLatency"
	MacroPodIngress_EvalSummary_FullMethodName    = "/macropod.MacroPodIngress/EvalSummary"
)

// MacroPodIngressClient is the client API for MacroPodIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MacroPodIngressClient interface {
	Config(ctx context.Context, in *ConfigStruct, opts ...grpc.CallOption) (*MacroPodReply, error)
	WorkflowInvoke(ctx context.Context, in *IngressRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	FunctionInvoke(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	CreateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error)
	UpdateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error)
	DeleteWorkflow(ctx context.Context, in *IngressRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	Eval(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error)
	EvalMetrics(ctx context.Context, in *IngressEvalRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	EvalLatency(ctx context.Context, in *IngressEvalRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
	EvalSummary(ctx context.Context, in *IngressEvalRequest, opts ...grpc.CallOption) (*MacroPodReply, error)
}

type macroPodIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewMacroPodIngressClient(cc grpc.ClientConnInterface) MacroPodIngressClient {
	return &macroPodIngressClient{cc}
}

func (c *macroPodIngressClient) Config(ctx context.Context, in *ConfigStruct, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) WorkflowInvoke(ctx context.Context, in *IngressRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_WorkflowInvoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) FunctionInvoke(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_FunctionInvoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) CreateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) UpdateWorkflow(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_UpdateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) DeleteWorkflow(ctx context.Context, in *IngressRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_DeleteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) Eval(ctx context.Context, in *WorkflowStruct, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_Eval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) EvalMetrics(ctx context.Context, in *IngressEvalRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_EvalMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) EvalLatency(ctx context.Context, in *IngressEvalRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_EvalLatency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroPodIngressClient) EvalSummary(ctx context.Context, in *IngressEvalRequest, opts ...grpc.CallOption) (*MacroPodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MacroPodReply)
	err := c.cc.Invoke(ctx, MacroPodIngress_EvalSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MacroPodIngressServer is the server API for MacroPodIngress service.
// All implementations must embed UnimplementedMacroPodIngressServer
// for forward compatibility.
type MacroPodIngressServer interface {
	Config(context.Context, *ConfigStruct) (*MacroPodReply, error)
	WorkflowInvoke(context.Context, *IngressRequest) (*MacroPodReply, error)
	FunctionInvoke(context.Context, *FunctionRequest) (*MacroPodReply, error)
	CreateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error)
	UpdateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error)
	DeleteWorkflow(context.Context, *IngressRequest) (*MacroPodReply, error)
	Eval(context.Context, *WorkflowStruct) (*MacroPodReply, error)
	EvalMetrics(context.Context, *IngressEvalRequest) (*MacroPodReply, error)
	EvalLatency(context.Context, *IngressEvalRequest) (*MacroPodReply, error)
	EvalSummary(context.Context, *IngressEvalRequest) (*MacroPodReply, error)
	mustEmbedUnimplementedMacroPodIngressServer()
}

// UnimplementedMacroPodIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMacroPodIngressServer struct{}

func (UnimplementedMacroPodIngressServer) Config(context.Context, *ConfigStruct) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedMacroPodIngressServer) WorkflowInvoke(context.Context, *IngressRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkflowInvoke not implemented")
}
func (UnimplementedMacroPodIngressServer) FunctionInvoke(context.Context, *FunctionRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FunctionInvoke not implemented")
}
func (UnimplementedMacroPodIngressServer) CreateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedMacroPodIngressServer) UpdateWorkflow(context.Context, *WorkflowStruct) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkflow not implemented")
}
func (UnimplementedMacroPodIngressServer) DeleteWorkflow(context.Context, *IngressRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkflow not implemented")
}
func (UnimplementedMacroPodIngressServer) Eval(context.Context, *WorkflowStruct) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Eval not implemented")
}
func (UnimplementedMacroPodIngressServer) EvalMetrics(context.Context, *IngressEvalRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvalMetrics not implemented")
}
func (UnimplementedMacroPodIngressServer) EvalLatency(context.Context, *IngressEvalRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvalLatency not implemented")
}
func (UnimplementedMacroPodIngressServer) EvalSummary(context.Context, *IngressEvalRequest) (*MacroPodReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvalSummary not implemented")
}
func (UnimplementedMacroPodIngressServer) mustEmbedUnimplementedMacroPodIngressServer() {}
func (UnimplementedMacroPodIngressServer) testEmbeddedByValue()                         {}

// UnsafeMacroPodIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MacroPodIngressServer will
// result in compilation errors.
type UnsafeMacroPodIngressServer interface {
	mustEmbedUnimplementedMacroPodIngressServer()
}

func RegisterMacroPodIngressServer(s grpc.ServiceRegistrar, srv MacroPodIngressServer) {
	// If the following call pancis, it indicates UnimplementedMacroPodIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MacroPodIngress_ServiceDesc, srv)
}

func _MacroPodIngress_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).Config(ctx, req.(*ConfigStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_WorkflowInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).WorkflowInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_WorkflowInvoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).WorkflowInvoke(ctx, req.(*IngressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_FunctionInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).FunctionInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_FunctionInvoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).FunctionInvoke(ctx, req.(*FunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).CreateWorkflow(ctx, req.(*WorkflowStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_UpdateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).UpdateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_UpdateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).UpdateWorkflow(ctx, req.(*WorkflowStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_DeleteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).DeleteWorkflow(ctx, req.(*IngressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_Eval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).Eval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_Eval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).Eval(ctx, req.(*WorkflowStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_EvalMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngressEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).EvalMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_EvalMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).EvalMetrics(ctx, req.(*IngressEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_EvalLatency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngressEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).EvalLatency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_EvalLatency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).EvalLatency(ctx, req.(*IngressEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroPodIngress_EvalSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngressEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroPodIngressServer).EvalSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroPodIngress_EvalSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroPodIngressServer).EvalSummary(ctx, req.(*IngressEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MacroPodIngress_ServiceDesc is the grpc.ServiceDesc for MacroPodIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MacroPodIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "macropod.MacroPodIngress",
	HandlerType: (*MacroPodIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Config",
			Handler:    _MacroPodIngress_Config_Handler,
		},
		{
			MethodName: "WorkflowInvoke",
			Handler:    _MacroPodIngress_WorkflowInvoke_Handler,
		},
		{
			MethodName: "FunctionInvoke",
			Handler:    _MacroPodIngress_FunctionInvoke_Handler,
		},
		{
			MethodName: "CreateWorkflow",
			Handler:    _MacroPodIngress_CreateWorkflow_Handler,
		},
		{
			MethodName: "UpdateWorkflow",
			Handler:    _MacroPodIngress_UpdateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _MacroPodIngress_DeleteWorkflow_Handler,
		},
		{
			MethodName: "Eval",
			Handler:    _MacroPodIngress_Eval_Handler,
		},
		{
			MethodName: "EvalMetrics",
			Handler:    _MacroPodIngress_EvalMetrics_Handler,
		},
		{
			MethodName: "EvalLatency",
			Handler:    _MacroPodIngress_EvalLatency_Handler,
		},
		{
			MethodName: "EvalSummary",
			Handler:    _MacroPodIngress_EvalSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "macropod.proto",
}
