apiVersion: v1
kind: Service
metadata:
  name: micro-rpc-a
spec:
  selector:
    app: micro-rpc-a
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: micro-rpc-b
spec:
  selector:
    app: micro-rpc-b
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-rpc-a
spec:
  selector:
    matchLabels:
      app: micro-rpc-a
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-rpc-a
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: micro-rpc-a
        image: arearnest7/micro-rpc-a:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: FUNC_PORT
            value: "5000"
          - name: GRPC_THREAD
            value: "10"
          - name: DEST
            value: "10.43.190.2:80"
          - name: LEN
            value: "1000000"
            value: micro-rpc-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-rpc-b
spec:
  selector:
    matchLabels:
      app: micro-rpc-b
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-rpc-b
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-4
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: micro-rpc-b
        image: arearnest7/micro-rpc-b:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: FUNC_PORT
            value: "5000"
          - name: GRPC_THREAD
            value: "10"
          - name: LEN
            value: "1000000"
            value: micro-rpc-b
