apiVersion: v1
kind: Service
metadata:
  name: macropod-service
spec:
  selector:
    app: macropod
  ports:
  - name: eval
    port: 8000
    targetPort: 8000
  - name: ingress
    port: 8001
    targetPort: 8001
  - name: deployer
    port: 8002
    targetPort: 8002
  - name: logger
    port: 8003
    targetPort: 8003
  - name: eval-http
    port: 9000
    targetPort: 9000
  - name: ingress-http
    port: 9001
    targetPort: 9001
  - name: deployer-http
    port: 9002
    targetPort: 9002
  - name: logger-http
    port: 9003
    targetPort: 9003
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: macropod-service-account
---
apiVersion: v1
kind: Namespace
metadata:
  name: macropod-functions
  labels:
    name: macropod-functions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macropod-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: macropod-role
subjects:
- kind: ServiceAccount
  name: macropod-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: macropod-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macropod-service
spec:
  selector:
    matchLabels:
      app: macropod
  replicas: 1
  template:
    spec:
      serviceAccountName: macropod-service-account
    metadata:
      labels:
        app: macropod
    spec:
     nodeSelector:
        kubernetes.io/hostname: sysdev-tamu-1
     serviceAccountName: macropod-service-account
     tolerations:
      - key: "master-node"
        value: "master-node"
        effect: "NoSchedule"
     containers:
      - name: macropod-eval
        image: sysdevtamu/macropod-eval:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 9000
        env:
        - name: SERVICE_PORT
          value: "8000"
        - name: HTTP_PORT
          value: "9000"
        - name: INGRESS_ADDRESS
          value: "127.0.0.1:8001"
        - name: METRICS_DIR
          value: "/app/metrics/"
        - name: LATENCY_DIR
          value: "/app/latency/"
        - name: SUMMARY_DIR
          value: "/app/summary/"
        - name: WORKER_NODES
          value: "192.168.1.19"
      - name: macropod-ingress
        image: sysdevtamu/macropod-ingress:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        - containerPort: 9001
        env:
        - name: SERVICE_PORT
          value: "8001"
        - name: HTTP_PORT
          value: "9001"
        - name: DEPLOYER_ADDRESS
          value: "127.0.0.1:8002"
        - name: NAMESPACE
          value: "macropod-functions"
        - name: TTL
          value: "180"
        - name: DEPLOYMENT
          value: "macropod"
        - name: COMMUNICATION
          value: "direct"
        - name: AGGREGATION
          value: "agg"
        - name: TARGET
          value: "-1"
        - name: DEBUG
          value: "5"
      - name: macropod-deployer
        image: sysdevtamu/macropod-deployer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        - containerPort: 9002
        env:
        - name: SERVICE_PORT
          value: "8002"
        - name: HTTP_PORT
          value: "9002"
        - name: NAMESPACE
          value: "macropod-functions"
        - name: INGRESS_ADDRESS
          value: "macropod-service.default.svc.cluster.local:8001"
        - name: LOGGER_ADDRESS
          value: "macropod-service.default.svc.cluster.local:8003"
        - name: TTL
          value: "180"
        - name: DEPLOYMENT
          value: "macropod"
        - name: COMMUNICATION
          value: "direct"
        - name: AGGREGATION
          value: "agg"
        - name: TARGET
          value: "-1"
        - name: DEBUG
          value: "5"
      - name: macropod-logger
        image: sysdevtamu/macropod-logger:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        - containerPort: 9003
        env:
        - name: SERVICE_PORT
          value: "8003"
        - name: HTTP_PORT
          value: "9003"
        - name: TIMESTAMP_DIR
          value: "/app/timestamp/"
        - name: ERROR_DIR
          value: "/app/error/"
        - name: PRINT_DIR
          value: "/app/print/"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: macropod-metric-server
spec:
  selector:
    matchLabels:
      name:  macropod-metric-server
  template:
    metadata:
      labels:
        name:  macropod-metric-server
    spec:
      containers:
        - name:  macropod-metric-server
          image: sysdevtamu/macropod-metrics:latest
          env:
          - name: SERVICE_PORT
            value: "10000"
          - name: HTTP_PORT
            value: "11000"
          ports:
            - name: http
              containerPort: 11000
              hostPort: 11000
            - name: grpc
              containerPort: 10000
              hostPort: 10000
