# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x08\x66unction\"0\n\x0bRequestBody\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\"+\n\x0cResponseBody\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32T\n\x0cgRPCFunction\x12\x44\n\x13gRPCFunctionHandler\x12\x15.function.RequestBody\x1a\x16.function.ResponseBodyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTBODY']._serialized_start=23
  _globals['_REQUESTBODY']._serialized_end=71
  _globals['_RESPONSEBODY']._serialized_start=73
  _globals['_RESPONSEBODY']._serialized_end=116
  _globals['_GRPCFUNCTION']._serialized_start=118
  _globals['_GRPCFUNCTION']._serialized_end=202
# @@protoc_insertion_point(module_scope)
