apiVersion: v1
kind: Service
metadata:
  name: feature-orchestrator
spec:
  selector:
    app: feature-orchestrator
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: feature-extractor
spec:
  selector:
    app: feature-extractor
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: v1
kind: Service
metadata:
  name: feature-wait
spec:
  selector:
    app: feature-wait
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.3
---
apiVersion: v1
kind: Service
metadata:
  name: feature-status
spec:
  selector:
    app: feature-status
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.4
---
apiVersion: v1
kind: Service
metadata:
  name: feature-reducer
spec:
  selector:
    app: feature-reducer
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-orchestrator
spec:
  selector:
    matchLabels:
      app: feature-orchestrator
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-orchestrator
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: feature-orchestrator
        image: sysdevtamu/feature-orchestrator:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: FEATURE_EXTRACTOR
            value: 10.43.190.2:80
          - name: FEATURE_WAIT
            value: 10.43.190.3:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-extractor
spec:
  selector:
    matchLabels:
      app: feature-extractor
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-extractor
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-4
      containers:
      - name: feature-extractor
        image: sysdevtamu/feature-extractor:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-wait
spec:
  selector:
    matchLabels:
      app: feature-wait
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-wait
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-5
      containers:
      - name: feature-wait
        image: sysdevtamu/feature-wait:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: FEATURE_STATUS
            value: 10.43.190.4:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-status
spec:
  selector:
    matchLabels:
      app: feature-status
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-status
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-3
      containers:
      - name: feature-status
        image: sysdevtamu/feature-status:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: FEATURE_WAIT
            value: 10.43.190.3:80
          - name: FEATURE_REDUCER
            value: 10.43.190.5:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-reducer
spec:
  selector:
    matchLabels:
      app: feature-reducer
  replicas: 1
  template:
    metadata:
      labels:
        app: feature-reducer
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-4
      containers:
      - name: feature-reducer
        image: sysdevtamu/feature-reducer:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
