apiVersion: v1
kind: Service
metadata:
  name: hotel-single-pod
spec:
  selector:
    app: hotel-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-single-pod
spec:
  selector:
    matchLabels:
      app: hotel-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: hotel-frontend
        image: sysdevtamu/hotel-frontend:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: HOTEL_SEARCH
            value: 127.0.0.1:5001
          - name: HOTEL_RECOMMEND
            value: 127.0.0.1:5002
          - name: HOTEL_RESERVE
            value: 127.0.0.1:5003
          - name: HOTEL_USER
            value: 127.0.0.1:5004
      - name: hotel-search
        image: sysdevtamu/hotel-search:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: HOTEL_GEO
            value: 127.0.0.1:5005
          - name: HOTEL_RATE
            value: 127.0.0.1:5007
      - name: hotel-recommend
        image: sysdevtamu/hotel-recommend:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
      - name: hotel-reserve
        image: sysdevtamu/hotel-reserve:macropod
        ports:
        - containerPort: 5003
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
      - name: hotel-user
        image: sysdevtamu/hotel-user:macropod
        ports:
        - containerPort: 5004
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
      - name: hotel-geo
        image: sysdevtamu/hotel-geo:macropod
        ports:
        - containerPort: 5005
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
      - name: hotel-profile
        image: sysdevtamu/hotel-profile:macropod
        ports:
        - containerPort: 5006
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5006"
      - name: hotel-rate
        image: sysdevtamu/hotel-rate:macropod
        ports:
        - containerPort: 5007
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5007"
