apiVersion: v1
kind: Service
metadata:
  name: pipelined-single-mmap
spec:
  selector:
    app: pipelined-single-mmap
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-single-mmap
spec:
  selector:
    matchLabels:
      app: pipelined-single-mmap
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-single-mmap
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: pipelined-main
        image: arearnest7/pipelined-main:macropod
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: PIPELINED_MAIN
            value: 127.0.0.1:5001
          - name: PIPELINED_CHECKSUM
            value: 127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: 127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: 127.0.0.1:5005
      - name: pipelined-main-2
        image: arearnest7/pipelined-main:macropod
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: PIPELINED_MAIN
            value: 127.0.0.1:5002
          - name: PIPELINED_CHECKSUM
            value: 127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: 127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: 127.0.0.1:5005
      - name: pipelined-main-3
        image: arearnest7/pipelined-main:macropod
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: APP_PV
            value: "/macropod-pv"
          - name: PIPELINED_MAIN
            value: 127.0.0.1:5001
          - name: PIPELINED_CHECKSUM
            value: 127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: 127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: 127.0.0.1:5005
      - name: pipelined-checksum
        image: arearnest7/pipelined-checksum:macropod
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
          - name: APP_PV
            value: "/macropod-pv"
      - name: pipelined-zip
        image: arearnest7/pipelined-zip:macropod
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
      - name: pipelined-encrypt
        image: arearnest7/pipelined-encrypt:macropod
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
