apiVersion: v1
kind: Service
metadata:
  name: pipelined-single-pod
spec:
  selector:
    app: pipelined-single-pod
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-single-pod
spec:
  selector:
    matchLabels:
      app: pipelined-single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-single-pod
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: pipelined-main
        image: sysdevtamu/pipelined-main:macropod
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5000"
          - name: PIPELINED_MAIN
            value: 127.0.0.1:5001
          - name: PIPELINED_CHECKSUM
            value: 127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: 127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: 127.0.0.1:5005
      - name: pipelined-main-2
        image: sysdevtamu/pipelined-main:macropod
        ports:
        - containerPort: 5001
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5001"
          - name: PIPELINED_MAIN
            value: 127.0.0.1:5002
          - name: PIPELINED_CHECKSUM
            value: 127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: 127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: 127.0.0.1:5005
      - name: pipelined-main-3
        image: sysdevtamu/pipelined-main:macropod
        ports:
        - containerPort: 5002
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5002"
          - name: PIPELINED_MAIN
            value: 127.0.0.1:5001
          - name: PIPELINED_CHECKSUM
            value: 127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: 127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: 127.0.0.1:5005
      - name: pipelined-checksum
        image: sysdevtamu/pipelined-checksum:macropod
        ports:
        - containerPort: 5003
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5003"
      - name: pipelined-zip
        image: sysdevtamu/pipelined-zip:macropod
        ports:
        - containerPort: 5004
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5004"
      - name: pipelined-encrypt
        image: sysdevtamu/pipelined-encrypt:macropod
        ports:
        - containerPort: 5005
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: GRPC_THREAD
            value: "10"
          - name: FUNC_PORT
            value: "5005"
