apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: election-gateway-vevp
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/election-gateway-vevp:wob
          env:
          - name: ELECTION_GET_RESULTS_PARTIAL
            value: http://election-get-results-partial.knative-functions.127.0.0.1.sslip.io
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: electoon-gateway-vevp
