apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: election-gateway
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/election-gateway:wob
          env:
          - name: ELECTION_GET_RESULTS
            value: http://election-get-results.default.127.0.0.1.sslip.io
          - name: ELECTION_VOTE_ENQUEUER
            value: http://election-vote-enqueuer.default.127.0.0.1.sslip.io
