apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-full
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/feature-full:wob
