apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-reducer
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/sysdevtamu/feature-reducer:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
