apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-extractor-partial
  namespace: knative-functions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/feature-extractor-partial:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
