apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-status
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/feature-status:kn
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: FEATURE_REDUCER
            value: http://feature-reducer.knative-functions.127.0.0.1.sslip.io
          - name: FEATURE_WAIT
            value: http://feature-wait.knative-functions.127.0.0.1.sslip.io
