apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-status
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/feature-status:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: FEATURE_REDUCER
            value: http://feature-reducer.default.10.125.188.34.sslip.io
          - name: FEATURE_WAIT
            value: http://feature-wait.default.10.125.188.34.sslip.io
