apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-wait
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/feature-wait:wob
          env:
          - name: FEATURE_STATUS
            value: http://feature-status.default.10.125.188.34.sslip.io
