apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-full
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/feature-full:wob
