apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hotel-frontend-spgr
  namespace: knative-functions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/hotel-frontend-spgr:wob
          env:
          - name: HOTEL_APP_DATABASE
            value: mongodb://10.42.2.96:27017
          - name: HOTEL_APP_MEMCACHED
            value: 10.42.4.93:11211
          - name: HOTEL_RECOMMEND_PARTIAL
            value: http://hotel-recommend-partial.knative-functions.127.0.0.1.sslip.io
          - name: HOTEL_RESERVE_PARTIAL
            value: http://hotel-reserve-partial.knative-functions.127.0.0.1.sslip.io
          - name: HOTEL_USER_PARTIAL
            value: http://hotel-user-partial.knative-functions.127.0.0.1.sslip.io
