apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hotel-search
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/hotel-search:wob
          env:
          - name: HOTEL_GEO
            value: http://hotel-geo.default.127.0.0.1.sslip.io
          - name: HOTEL_RATE
            value: http://hotel-rate.default.127.0.0.1.sslip.io
