apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hotel-frontend
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/hotel-frontend:kn
          env:
          - name: HOTEL_SEARCH
            value: http://hotel-search.knative-functions.127.0.0.1.sslip.io
          - name: HOTEL_RECOMMEND
            value: http://hotel-recommend.knative-functions.127.0.0.1.sslip.io
          - name: HOTEL_RESERVE
            value: http://hotel-reserve.knative-functions.127.0.0.1.sslip.io
          - name: HOTEL_USER
            value: http://hotel-user.knative-functions.127.0.0.1.sslip.io
