apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hotel-frontend
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/hotel-frontend:wob
          env:
          - name: HOTEL_SEARCH
            value: http://hotel-search.default.10.125.188.34.sslip.io
          - name: HOTEL_RECOMMEND
            value: http://hotel-recommend.default.10.125.188.34.sslip.io
          - name: HOTEL_RESERVE
            value: http://hotel-reserve.default.10.125.188.34.sslip.io
          - name: HOTEL_USER
            value: http://hotel-user.default.10.125.188.34.sslip.io
