apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pipelined-main
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/pipelined-main:wob
          env:
          - name: PIPELINED_CHECKSUM
            value: http://pipelined-checksum.default.10.125.188.34.sslip.io
          - name: PIPELINED_ZIP
            value: http://pipelined-zip.default.10.125.188.34.sslip.io
          - name: PIPELINED_ENCRYPT
            value: http://pipelined-encrypt.default.10.125.188.34.sslip.io
          - name: PIPELINED_MAIN
            value: http://pipelined-main.default.10.125.188.34.sslip.io
