apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pipelined-main-partial
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/pipelined-main-partial:wob
          env:
          - name: PIPELINED_CHECKSUM_PARTIAL
            value: http://pipelined-checksum-partial.default.10.125.188.34.sslip.io
          - name: PIPELINED_ZIP_PARTIAL
            value: http://pipelined-zip-partial.default.10.125.188.34.sslip.io
          - name: PIPELINED_ENCRYPT_PARTIAL
            value: http://pipelined-encrypt-partial.default.10.125.188.34.sslip.io
