apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pipelined-zip-partial
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/pipelined-zip-partial:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
