apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pipelined-main-partial
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/pipelined-main-partial:wob
          env:
          - name: PIPELINED_CHECKSUM_PARTIAL
            value: http://pipelined-checksum-partial.knative-functions.127.0.0.1.sslip.io
          - name: PIPELINED_ZIP_PARTIAL
            value: http://pipelined-zip-partial.knative-functions.127.0.0.1.sslip.io
          - name: PIPELINED_ENCRYPT_PARTIAL
            value: http://pipelined-encrypt-partial.knative-functions.127.0.0.1.sslip.io
