apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-product-or-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-product-or-service:wob
          env:
          - name: SENTIMENT_PRODUCT_SENTIMENT
            value: http://sentiment-product-sentiment.default.127.0.0.1.sslip.io
          - name: SENTIMENT_SERVICE_SENTIMENT
            value: http://sentiment-service-sentiment.default.127.0.0.1.sslip.io
          - name: SENTIMENT_CFAIL
            value: http://sentiment-cfail.default.127.0.0.1.sslip.io
