apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-product-sentiment-prs
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/sysdevtamu/sentiment-product-sentiment-prs:wob
          env:
          - name: SENTIMENT_DB_S
            value: http://sentiment-db-s.knative-functions.127.0.0.1.sslip.io
