apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-service-sentiment
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-service-sentiment:wob
          env:
          - name: SENTIMENT_SERVICE_RESULT
            value: http://sentiment-service-result.default.127.0.0.1.sslip.io
