apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-product-sentiment
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-product-sentiment:wob
          env:
          - name: SENTIMENT_PRODUCT_RESULT
            value: http://sentiment-product-result.knative-functions.127.0.0.1.sslip.io
