apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-cfail
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-cfail:kn
