apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-sfail
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/sysdevtamu/sentiment-sfail:wob
