apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-service-result
  namespace: knative-functions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-service-result:wob
          env:
          - name: SENTIMENT_DB
            value: http://sentiment-db.knative-functions.127.0.0.1.sslip.io
          - name: SENTIMENT_SNS
            value: http://sentiment-sns.knative-functions.127.0.0.1.sslip.io
          - name: SENTIMENT_SFAIL
            value: http://sentiment-sfail.knative-functions.127.0.0.1.sslip.io
