apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-main-rcposc
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-main-rcposc:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: SENTIMENT_PRODUCT_SENTIMENT_PRS
            value: http://sentiment-product-sentiment-prs.default.127.0.0.1.sslip.io
          - name: SENTIMENT_SERVICE_SENTIMENT_SRS
            value: http://sentiment-service-sentiment-srs.default.127.0.0.1.sslip.io
