apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-sns
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-sns:wob
          env:
          - name: SENTIMENT_DB
            value: http://sentiment-db.default.10.125.188.34.sslip.io
