apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-main
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-main:kn
          env:
          - name: SENTIMENT_READ_CSV
            value: http://sentiment-read-csv.knative-functions.127.0.0.1.sslip.io
