apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-main
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-main:wob
          env:
          - name: SENTIMENT_READ_CSV
            value: http://sentiment-read-csv.default.10.125.188.34.sslip.io
