apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-read-csv
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-read-csv:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: SENTIMENT_PRODUCT_OR_SERVICE
            value: http://sentiment-product-or-service.default.127.0.0.1.sslip.io
