apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-service-sentiment-srs
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-service-sentiment-srs:wob
          env:
          - name: SENTIMENT_DB_S
            value: http://sentiment-db-s.default.10.125.188.34.sslip.io
