apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-sfail
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-sfail:wob
