apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sentiment-service-result
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/sentiment-service-result:wob
          env:
          - name: SENTIMENT_DB
            value: http://sentiment-db.default.10.125.188.34.sslip.io
          - name: SENTIMENT_SNS
            value: http://sentiment-sns.default.10.125.188.34.sslip.io
          - name: SENTIMENT_SFAIL
            value: http://sentiment-sfail.default.10.125.188.34.sslip.io
