apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-streaming-d
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/video-streaming-d:wob
          env:
          - name: VIDEO_RECOG_PARTIAL
            value: http://video-recog-partial.default.10.125.188.34.sslip.io
