apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-streaming-d
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/video-streaming-d:wob
          env:
          - name: VIDEO_RECOG_PARTIAL
            value: http://video-recog-partial.knative-functions.127.0.0.1.sslip.io
