apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-decoder
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/video-decoder:kn
          env:
          - name: VIDEO_RECOG
            value: http://video-recog.knative-functions.127.0.0.1.sslip.io
