apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-streaming
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/video-streaming:wob
          env:
          - name: VIDEO_DECODER
            value: http://video-decoder.default.10.125.188.34.sslip.io
