apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-recog
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/video-recog:wob
