apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-recog-partial
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/sysdevtamu/video-recog-partial:wob
