apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-stats
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/wage-stats:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: WAGE_SUM
            value: http://wage-sum.default.10.125.188.34.sslip.io
