apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-stats-partial
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/wage-stats-partial:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: WAGE_SUM_AMW
            value: http://wage-sum-amw.knative-functions.127.0.0.1.sslip.io
