apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-full
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/sysdevtamu/wage-full:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: WAGE_FULL
            value: http://wage-full.knative-functions.127.0.0.1.sslip.io
