apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-format
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/wage-format:wob
          env:
          - name: WAGE_WRITE_RAW
            value: http://wage-write-raw.default.10.125.188.34.sslip.io
