apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-sum-amw
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/arearnest7/wage-sum-amw:kn
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
