apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-full
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/wage-full:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: WAGE_FULL
            value: http://wage-full.default.10.125.188.34.sslip.io
