apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-merit
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/wage-merit:wob
          env:
          - name: WAGE_WRITE_MERIT
            value: http://wage-write-merit.default.127.0.0.1.sslip.io
