apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-validator-fw
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/arearnest7/wage-validator-fw:wob
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
          - name: WAGE_STATS_PARTIAL
            value: http://wage-stats-partial.default.127.0.0.1.sslip.io
