apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: election-get-results
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/sysdevtamu/election-get-results:kn
          env:
          - name: REDIS_URL
            value: 127.0.0.1
          - name: REDIS_PASSWORD
            value: password
