apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-unified
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
        - image: docker.io/sysdevtamu/video-unified:kn
