
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelined-0
  namespace: default
  labels: 
    "cpu_threshold_1": "100"
    "cpu_threshold_2" : "300"
    "mm_threshold_1" : "100000000"
    "mm_threshold_2" : "10000000000"
    "function_name" : "pipelined"
    "kind" : "mmap"
data:
  my-config.json: |
    [
        {
          "endpoints": "pipelined-chec,pipelined-recommend,pipelined-reserve,pipelined-user",
          "name": "pipelined-main",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-frontend:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            }, 
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 80,
            "targetPort": 5000
          },
          "ingress": {
            "host": "pipelined.example.com"
          }
        },
        {
          "endpoints": "pipelined-geo,pipelined-rate",
          "name": "pipelined-search",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-search:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5001"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5001,
            "targetPort": 5001
          }
        },
        {
          "name": "pipelined-recommend",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-recommend:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5002"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5002,
            "targetPort": 5002
          }
        },
        {
          "name": "pipelined-reserve",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-reserve:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5003"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5003,
            "targetPort": 5003
          }
        },
        {
          "name": "pipelined-user",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-user:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5004"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5004,
            "targetPort": 5004
          }
        },
        {
          "name": "pipelined-geo",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-geo:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5005"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5005,
            "targetPort": 5005
          }
        },
        {
          "name": "pipelined-profile",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-profile:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5006"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5006,
            "targetPort": 5006
          }
        },
        {
          "name": "pipelined-rate",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-rate:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5006"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5006,
            "targetPort": 5006
          }
        }
      ]


---





apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelined-1
  namespace: default
  labels: 
    "cpu_threshold_1": "100"
    "cpu_threshold_2" : "600"
    "mm_threshold_1" : "100000000"
    "mm_threshold_2" : "10000000000"
    "function_name" : "pipelined"
    "kind" : "single-pod"
data:
  my-config.json: |
    [
        {
          "endpoints": "pipelined-search,pipelined-recommend,pipelined-reserve,pipelined-user",
          "name": "pipelined-frontend",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-frontend:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 80,
            "targetPort": 5000
          },
          "ingress": {
            "host": "pipelined.example.com"
          }
        },
        {
          "endpoints": "pipelined-geo,pipelined-rate",
          "name": "pipelined-search",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-search:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5001"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5001,
            "targetPort": 5001
          }
        },
        {
          "name": "pipelined-recommend",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-recommend:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5002"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5002,
            "targetPort": 5002
          }
        },
        {
          "name": "pipelined-reserve",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-reserve:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5003"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5003,
            "targetPort": 5003
          }
        },
        {
          "name": "pipelined-user",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-user:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5004"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5004,
            "targetPort": 5004
          }
        },
        {
          "name": "pipelined-geo",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-geo:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5005"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5005,
            "targetPort": 5005
          }
        },
        {
          "name": "pipelined-profile",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-profile:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5006"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5006,
            "targetPort": 5006
          }
        },
        {
          "name": "pipelined-rate",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/pipelined-rate:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5007"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5007,
            "targetPort": 5007
          }
        }
      ]



---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelined-2
  namespace: default
  labels: 
    "cpu_threshold_1": "200000"
    "cpu_threshold_2" : "4000000"
    "mm_threshold_1" : "100000000"
    "mm_threshold_2" : "10000000000"
    "function_name" : "pipelined"
    "kind" : "multi-pod"
data:
  my-config.json: |
    [
      {
        "endpoints": "pipelined-search,pipelined-recommend,pipelined-reserve,pipelined-user",
        "name": "pipelined-frontend",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-frontend:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 80,
          "targetPort": 5000
        },
        "ingress": {
          "host": "pipelined.example.com"
        }
      },
      {
        "endpoints": "pipelined-geo,pipelined-rate",
        "name": "pipelined-search",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-search:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 443,
          "targetPort": 5000
        }
      },
      {
        "name": "pipelined-recommend",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-recommend:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 443,
          "targetPort": 5000
        }
      },
      {
        "name": "pipelined-reserve",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-reserve:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 443,
          "targetPort": 5000
        }
      },
      {
        "name": "pipelined-user",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-user:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 443,
          "targetPort": 5000
        }
      },
      {
        "name": "pipelined-geo",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-geo:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 443,
          "targetPort": 5000
        }
      },
      {
        "name": "pipelined-profile",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-profile:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 443,
          "targetPort": 5000
        }
      },
      {
        "name": "pipelined-rate",
        "version": 1,
        "replicaCount": 1,
        "image": {
          "image": "arearnest7/pipelined-rate:macropod",
          "pullPolicy": "IfNotPresent"
        },
        "env": [{
          "name": "SERVICE_TYPE",
          "value": "GRPC"
          },
          {
          "name": "GRPC_THREAD",
          "value": "10"
          }, 
          {
            "name": "FUNC_PORT",
            "value": "5000"
          }
        ],
        "service": {
          "type": "ClusterIP",
          "port": 443,
          "targetPort": 5000
        }
      }
    ]



