


apiVersion: v1
kind: ConfigMap
metadata:
  name: wage-0
  namespace: default
  labels: 
    "cpu_threshold_1": "100"
    "cpu_threshold_2" : "300"
    "mm_threshold_1" : "100000000"
    "mm_threshold_2" : "10000000000"
    "function_name" : "wage"
    "kind" : "mmap"
data:
  my-config.json: |
    [
        {
          "endpoints": "wage-format",
          "name": "wage-validator",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-validator:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "HTTP"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            }, 
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 80,
            "targetPort": 5000
          },
          "ingress": {
            "host": "wage.example.com"
          }
        },
        {
          "endpoints": "wage-write-raw",
          "name": "wage-format",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-format:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5001"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5001,
            "targetPort": 5001
          }
        },
        {
          "endpoints": "wage-stats",
          "name": "wage-write-raw",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-write-raw:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5002"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5002,
            "targetPort": 5002
          }
        },
        {
          "endpoints": "wage-sum",
          "name": "wage-stats",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-stats:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5003"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5003,
            "targetPort": 5003
          }
        },
        {
          "endpoints": "wage-avg",
          "name": "wage-sum",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-sum:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5004"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5004,
            "targetPort": 5004
          }
        },
        {
          "endpoints": "wage-merit",
          "name": "wage-avg",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-avg:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5005"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5005,
            "targetPort": 5005
          }
        },
        {
          "endpoints": "wage-write-merit",
          "name": "wage-merit",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-merit:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "RPC_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "RPC_DEST_PV",
            "value": "/macropod-pv"
            },
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5006"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5006,
            "targetPort": 5006
          }
        },
        {
          "name": "wage-write-merit",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-write-merit:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
            "name": "APP_PV",
            "value": "/macropod-pv"
            },
            {
              "name": "FUNC_PORT",
              "value": "5007"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5007,
            "targetPort": 5007
          }
        }
      ]


---





apiVersion: v1
kind: ConfigMap
metadata:
  name: wage-1
  namespace: default
  labels: 
    "cpu_threshold_1": "100"
    "cpu_threshold_2" : "1300"
    "mm_threshold_1" : "100000000"
    "mm_threshold_2" : "10000000000"
    "function_name" : "wage"
    "kind" : "single-pod"
data:
  my-config.json: |
    [
        {
          "endpoints": "wage-format",
          "name": "wage-validator",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-validator:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "HTTP"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 80,
            "targetPort": 5000
          },
          "ingress": {
            "host": "wage.example.com"
          }
        },
        {
          "endpoints": "wage-write-raw",
          "name": "wage-format",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-format:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5001"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5001,
            "targetPort": 5001
          }
        },
        {
          "endpoints": "wage-stats",
          "name": "wage-write-raw",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-write-raw:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5002"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5002,
            "targetPort": 5002
          }
        },
        {
          "endpoints": "wage-sum",
          "name": "wage-stats",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-stats:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5003"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5003,
            "targetPort": 5003
          }
        },
        {
          "endpoints": "wage-avg",
          "name": "wage-sum",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-sum:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5004"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5004,
            "targetPort": 5004
          }
        },
        {
          "endpoints": "wage-merit",
          "name": "wage-avg",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-avg:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5005"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5005,
            "targetPort": 5005
          }
        },
        {
          "endpoints": "wage-write-merit",
          "name": "wage-merit",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-merit:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5006"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5006,
            "targetPort": 5006
          }
        },
        {
          "name": "wage-write-merit",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-write-merit:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5007"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 5007,
            "targetPort": 5007
          }
        }
      ]




---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wage-2
  namespace: default
  labels: 
    "cpu_threshold_1": "200000"
    "cpu_threshold_2" : "4000000"
    "mm_threshold_1" : "100000000"
    "mm_threshold_2" : "10000000000"
    "function_name" : "video-analytics"
    "kind" : "multi-pod"
data:
  my-config.json: |
    [
        {
          "endpoints": "wage-format",
          "name": "wage-validator",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-validator:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "HTTP"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          },
          "ingress": {
            "host": "wage.example.com"
          }
        },
        {
          "endpoints": "wage-write-raw",
          "name": "wage-format",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-format:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          }
        },
        {
          "endpoints": "wage-stats",
          "name": "wage-write-raw",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-write-raw:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          }
        },
        {
          "endpoints": "wage-sum",
          "name": "wage-stats",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-stats:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          }
        },
        {
          "endpoints": "wage-avg",
          "name": "wage-sum",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-sum:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          }
        },
        {
          "endpoints": "wage-merit",
          "name": "wage-avg",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-avg:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          }
        },
        {
          "endpoints": "wage-write-merit",
          "name": "wage-merit",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-merit:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          }
        },
        {
          "name": "wage-write-merit",
          "version": 1,
          "replicaCount": 1,
          "image": {
            "image": "arearnest7/wage-write-merit:macropod",
            "pullPolicy": "IfNotPresent"
          },
          "env": [{
            "name": "SERVICE_TYPE",
            "value": "GRPC"
            },
            {
            "name": "GRPC_THREAD",
            "value": "10"
            }, 
            {
              "name": "FUNC_PORT",
              "value": "5000"
            }
          ],
          "service": {
            "type": "ClusterIP",
            "port": 443,
            "targetPort": 5000
          }
        }
      ]


