apiVersion: v1
kind: Service
metadata:
  name: election-single-oci
spec:
  selector:
    app: election-single-oci
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-single-oci
spec:
  selector:
    matchLabels:
      app: election-single-oci
  replicas: 1
  template:
    metadata:
      labels:
        app: election-single-oci
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: election-gateway
        image: arearnest7/election-gateway:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: ELECTION_GET_RESULTS
            value: http://127.0.0.1:5001
          - name: ELECTION_VOTE_ENQUEUER
            value: http://127.0.0.1:5002
      - name: election-get-results
        image: arearnest7/election-get-results:oci
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
      - name: election-vote-enqueuer
        image: arearnest7/election-vote-enqueuer:oci
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: ELECTION_VOTE_PROCESSOR
            value: http://127.0.0.1:5003
      - name: election-vote-processor
        image: arearnest7/election-vote-processor:oci
        ports:
        - containerPort: 5003
        env:
          - name: PORT
            value: "5003"
