apiVersion: v1
kind: Service
metadata:
  name: election-gateway
spec:
  selector:
    app: election-gateway
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: election-get-results
spec:
  selector:
    app: election-get-results
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: v1
kind: Service
metadata:
  name: election-vote-enqueuer
spec:
  selector:
    app: election-vote-enqueuer
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.3
---
apiVersion: v1
kind: Service
metadata:
  name: election-vote-processor
spec:
  selector:
    app: election-vote-processor
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-gateway
spec:
  selector:
    matchLabels:
      app: election-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: election-gateway
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: election-gateway
        image: sysdevtamu/election-gateway:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: ELECTION_GET_RESULTS
            value: http://10.43.190.2:80
          - name: ELECTION_VOTE_ENQUEUER
            value: http://10.43.190.3:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-get-results
spec:
  selector:
    matchLabels:
      app: election-get-results
  replicas: 1
  template:
    metadata:
      labels:
        app: election-get-results
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-4
      containers:
      - name: election-get-results
        image: sysdevtamu/election-get-results:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-vote-enqueuer
spec:
  selector:
    matchLabels:
      app: election-vote-enqueuer
  replicas: 1
  template:
    metadata:
      labels:
        app: election-vote-enqueuer
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-5
      containers:
      - name: election-vote-enqueuer
        image: sysdevtamu/election-vote-enqueuer:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: ELECTION_VOTE_PROCESSOR
            value: http://10.43.190.4:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-vote-processor
spec:
  selector:
    matchLabels:
      app: election-vote-processor
  replicas: 1
  template:
    metadata:
      labels:
        app: election-vote-processor
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-3
      containers:
      - name: election-vote-processor
        image: sysdevtamu/election-vote-processor:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
