apiVersion: v1
kind: Service
metadata:
  name: hotel-frontend
spec:
  selector:
    app: hotel-frontend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-search
spec:
  selector:
    app: hotel-search
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-recommend
spec:
  selector:
    app: hotel-recommend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.3
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-reserve
spec:
  selector:
    app: hotel-reserve
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.4
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-user
spec:
  selector:
    app: hotel-user
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.5
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-geo
spec:
  selector:
    app: hotel-geo
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.6
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-profile
spec:
  selector:
    app: hotel-profile
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.7
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-rate
spec:
  selector:
    app: hotel-rate
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
spec:
  selector:
    matchLabels:
      app: hotel-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: hotel-frontend
        image: arearnest7/hotel-frontend:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: HOTEL_SEARCH
            value: http://10.43.190.2:80
          - name: HOTEL_RECOMMEND
            value: http://10.43.190.3:80
          - name: HOTEL_RESERVE
            value: http://10.43.190.4:80
          - name: HOTEL_USER
            value: http://10.43.190.5:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-search
spec:
  selector:
    matchLabels:
      app: hotel-search
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-search
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-4
      containers:
      - name: hotel-search
        image: arearnest7/hotel-search:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: HOTEL_GEO
            value: http://10.43.190.6:80
          - name: HOTEL_RATE
            value: http://10.43.190.8:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-recommend
spec:
  selector:
    matchLabels:
      app: hotel-recommend
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-recommend
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-5
      containers:
      - name: hotel-recommend
        image: arearnest7/hotel-recommend:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-reserve
spec:
  selector:
    matchLabels:
      app: hotel-reserve
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-reserve
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-4
      containers:
      - name: hotel-reserve
        image: arearnest7/hotel-reserve:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-user
spec:
  selector:
    matchLabels:
      app: hotel-user
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-user
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-5
      containers:
      - name: hotel-user
        image: arearnest7/hotel-user:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-geo
spec:
  selector:
    matchLabels:
      app: hotel-geo
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-geo
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-3
      containers:
      - name: hotel-geo
        image: arearnest7/hotel-geo:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-profile
spec:
  selector:
    matchLabels:
      app: hotel-profile
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-profile
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: hotel-profile
        image: arearnest7/hotel-profile:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-rate
spec:
  selector:
    matchLabels:
      app: hotel-rate
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel-rate
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-3
      containers:
      - name: hotel-rate
        image: arearnest7/hotel-rate:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
