apiVersion: v1
kind: Service
metadata:
  name: pipelined-main
spec:
  selector:
    app: pipelined-main
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-main-2
spec:
  selector:
    app: pipelined-main-2
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.2
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-main-3
spec:
  selector:
    app: pipelined-main-3
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.3
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-checksum
spec:
  selector:
    app: pipelined-checksum
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.4
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-zip
spec:
  selector:
    app: pipelined-zip
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.5
---
apiVersion: v1
kind: Service
metadata:
  name: pipelined-encrypt
spec:
  selector:
    app: pipelined-encrypt
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-main
spec:
  selector:
    matchLabels:
      app: pipelined-main
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-main
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: pipelined-main
        image: arearnest7/pipelined-main:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: PIPELINED_MAIN
            value: http://10.43.190.2:80
          - name: PIPELINED_CHECKSUM
            value: http://10.43.190.4:80
          - name: PIPELINED_ZIP
            value: http://10.43.190.5:80
          - name: PIPELINED_ENCRYPT
            value: http://10.43.190.6:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-main-2
spec:
  selector:
    matchLabels:
      app: pipelined-main-2
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-main-2
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-1
      containers:
      - name: pipelined-main-2
        image: arearnest7/pipelined-main:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: PIPELINED_MAIN
            value: http://10.43.190.3:80
          - name: PIPELINED_CHECKSUM
            value: http://10.43.190.4:80
          - name: PIPELINED_ZIP
            value: http://10.43.190.5:80
          - name: PIPELINED_ENCRYPT
            value: http://10.43.190.6:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-main-3
spec:
  selector:
    matchLabels:
      app: pipelined-main-3
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-main-3
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-3
      containers:
      - name: pipelined-main-3
        image: arearnest7/pipelined-main:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: PIPELINED_MAIN
            value: http://10.43.190.2:80
          - name: PIPELINED_CHECKSUM
            value: http://10.43.190.4:80
          - name: PIPELINED_ZIP
            value: http://10.43.190.5:80
          - name: PIPELINED_ENCRYPT
            value: http://10.43.190.6:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-checksum
spec:
  selector:
    matchLabels:
      app: pipelined-checksum
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-checksum
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-4
      containers:
      - name: pipelined-checksum
        image: arearnest7/pipelined-checksum:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-zip
spec:
  selector:
    matchLabels:
      app: pipelined-zip
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-zip
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-5
      containers:
      - name: pipelined-zip
        image: arearnest7/pipelined-zip:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-encrypt
spec:
  selector:
    matchLabels:
      app: pipelined-encrypt
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-encrypt
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-4
      containers:
      - name: pipelined-encrypt
        image: arearnest7/pipelined-encrypt:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
