apiVersion: v1
kind: Service
metadata:
  name: pipelined-single-oci
spec:
  selector:
    app: pipelined-single-oci
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelined-single-oci
spec:
  selector:
    matchLabels:
      app: pipelined-single-oci
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelined-single-oci
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: pipelined-main
        image: arearnest7/pipelined-main:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: PIPELINED_MAIN
            value: http://127.0.0.1:5001
          - name: PIPELINED_CHECKSUM
            value: http://127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: http://127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: http://127.0.0.1:5005
      - name: pipelined-main-2
        image: arearnest7/pipelined-main:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: PIPELINED_MAIN
            value: http://127.0.0.2:5000
          - name: PIPELINED_CHECKSUM
            value: http://127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: http://127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: http://127.0.0.1:5005
      - name: pipelined-main-3
        image: arearnest7/pipelined-main:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: PIPELINED_MAIN
            value: http://127.0.0.1:5001
          - name: PIPELINED_CHECKSUM
            value: http://127.0.0.1:5003
          - name: PIPELINED_ZIP
            value: http://127.0.0.1:5004
          - name: PIPELINED_ENCRYPT
            value: http://127.0.0.1:5005
      - name: pipelined-checksum
        image: arearnest7/pipelined-checksum:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        env:
          - name: PORT
            value: "5003"
      - name: pipelined-zip
        image: arearnest7/pipelined-zip:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        env:
          - name: PORT
            value: "5004"
      - name: pipelined-encrypt
        image: arearnest7/pipelined-encrypt:oci
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        env:
          - name: PORT
            value: "5005"
