apiVersion: v1
kind: Service
metadata:
  name: sentiment-single-oci
spec:
  selector:
    app: sentiment-single-oci
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-single-oci
spec:
  selector:
    matchLabels:
      app: sentiment-single-oci
  replicas: 1
  template:
    metadata:
      labels:
        app: sentiment-single-oci
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: sentiment-main
        image: sysdevtamu/sentiment-main:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: SENTIMENT_READ_CSV
            value: http://127.0.0.1:5001
      - name: sentiment-read-csv
        image: sysdevtamu/sentiment-read-csv:oci
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: SENTIMENT_PRODUCT_OR_SERVICE
            value: http://127.0.0.1:5002
      - name: sentiment-product-or-service
        image: sysdevtamu/sentiment-product-or-service:oci
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: SENTIMENT_CFAIL
            value: http://127.0.0.1:5003
          - name: SENTIMENT_PRODUCT_SENTIMENT
            value: http://127.0.0.1:5004
          - name: SENTIMENT_SERVICE_SENTIMENT
            value: http://127.0.0.1:5009
      - name: sentiment-cfail
        image: sysdevtamu/sentiment-cfail:oci
        ports:
        - containerPort: 5003
        env:
          - name: PORT
            value: "5003"
      - name: sentiment-product-sentiment
        image: sysdevtamu/sentiment-product-sentiment:oci
        ports:
        - containerPort: 5004
        env:
          - name: PORT
            value: "5004"
          - name: SENTIMENT_PRODUCT_RESULT
            value: http://127.0.0.1:5005
      - name: sentiment-product-result
        image: sysdevtamu/sentiment-product-result:oci
        ports:
        - containerPort: 5005
        env:
          - name: PORT
            value: "5005"
          - name: SENTIMENT_SFAIL
            value: http://127.0.0.1:5006
          - name: SENTIMENT_SNS
            value: http://127.0.0.1:5007
          - name: SENTIMENT_DB
            value: http://127.0.0.1:5008
      - name: sentiment-sfail
        image: sysdevtamu/sentiment-sfail:oci
        ports:
        - containerPort: 5006
        env:
          - name: PORT
            value: "5006"
      - name: sentiment-sns
        image: sysdevtamu/sentiment-sns:oci
        ports:
        - containerPort: 5007
        env:
          - name: PORT
            value: "5007"
          - name: SENTIMENT_DB
            value: http://127.0.0.1:5008
      - name: sentiment-db
        image: sysdevtamu/sentiment-db:oci
        ports:
        - containerPort: 5008
        env:
          - name: PORT
            value: "5008"
      - name: sentiment-service-sentiment
        image: sysdevtamu/sentiment-service-sentiment:oci
        ports:
        - containerPort: 5009
        env:
          - name: PORT
            value: "5009"
          - name: SENTIMENT_SERVICE_RESULT
            value: http://127.0.0.1:5010
      - name: sentiment-service-result
        image: sysdevtamu/sentiment-service-result:oci
        ports:
        - containerPort: 5010
        env:
          - name: PORT
            value: "5010"
          - name: SENTIMENT_SFAIL
            value: http://127.0.0.1:5006
          - name: SENTIMENT_SNS
            value: http://127.0.0.1:5007
          - name: SENTIMENT_DB
            value: http://127.0.0.1:5008
