apiVersion: v1
kind: Service
metadata:
  name: video-single-oci
spec:
  selector:
    app: video-single-oci
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-single-oci
spec:
  selector:
    matchLabels:
      app: video-single-oci
  replicas: 1
  template:
    metadata:
      labels:
        app: video-single-oci
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: video-streaming
        image: sysdevtamu/video-streaming:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: VIDEO_DECODER
            value: http://127.0.0.1:5001
      - name: video-decoder
        image: sysdevtamu/video-decoder:oci
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: VIDEO_RECOG
            value: http://127.0.0.1:5002
      - name: video-recog
        image: sysdevtamu/video-recog:oci
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
