apiVersion: v1
kind: Service
metadata:
  name: wage-single-oci
spec:
  selector:
    app: wage-single-oci
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wage-single-oci
spec:
  selector:
    matchLabels:
      app: wage-single-oci
  replicas: 1
  template:
    metadata:
      labels:
        app: wage-single-oci
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      containers:
      - name: wage-validator
        image: sysdevtamu/wage-validator:oci
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: WAGE_FORMAT
            value: http://127.0.0.1:5001
      - name: wage-format
        image: sysdevtamu/wage-format:oci
        ports:
        - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: WAGE_WRITE_RAW
            value: http://127.0.0.1:5002
      - name: wage-write-raw
        image: sysdevtamu/wage-write-raw:oci
        ports:
        - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: WAGE_STATS
            value: http://127.0.0.1:5003
      - name: wage-stats
        image: sysdevtamu/wage-stats:oci
        ports:
        - containerPort: 5003
        env:
          - name: PORT
            value: "5003"
          - name: WAGE_SUM
            value: http://127.0.0.1:5004
      - name: wage-sum
        image: sysdevtamu/wage-sum:oci
        ports:
        - containerPort: 5004
        env:
          - name: PORT
            value: "5004"
          - name: WAGE_AVG
            value: http://127.0.0.1:5005
      - name: wage-avg
        image: sysdevtamu/wage-avg:oci
        ports:
        - containerPort: 5005
        env:
          - name: PORT
            value: "5005"
          - name: WAGE_MERIT
            value: http://127.0.0.1:5006
      - name: wage-merit
        image: sysdevtamu/wage-merit:oci
        ports:
        - containerPort: 5006
        env:
          - name: PORT
            value: "5006"
          - name: WAGE_WRITE_MERIT
            value: http://127.0.0.1:5007
      - name: wage-write-merit
        image: sysdevtamu/wage-write-merit:oci
        ports:
        - containerPort: 5007
        env:
          - name: PORT
            value: "5007"
