apiVersion: v1
kind: Service
metadata:
  name: micro-rpc-mmap
spec:
  selector:
    app: micro-rpc-mmap
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-rpc-mmap
spec:
  selector:
    matchLabels:
      app: micro-rpc-mmap
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-rpc-mmap
    spec:
      nodeSelector:
        kubernetes.io/hostname: sys-dev-vm-2
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: micro-rpc-a
        image: sysdevtamu/micro-rpc-a:macropod
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: FUNC_PORT
            value: "5000"
          - name: GRPC_THREAD
            value: "10"
          - name: RPC_PV
            value: "/macropod-pv"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: DEST
            value: "127.0.0.1:5001"
          - name: LEN
            value: "1000000"
      - name: micro-rpc-b
        image: sysdevtamu/micro-rpc-b:macropod
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: FUNC_PORT
            value: "5001"
          - name: GRPC_THREAD
            value: "10"
          - name: APP_PV
            value: "/macropod-pv"
          - name: LEN
            value: "1000000"
