apiVersion: v1
kind: Secret
metadata:
  name: hotel-app
type: Opaque
stringData:
  hotel-app-database: http://hotel-app-database.default.10.125.188.36.sslip.io
  hotel-app-memcached: http://hotel-app-mmc.default.10.125.188.36.sslip.io
