apiVersion: v1
kind: Secret
metadata:
  name: partial-hotel
type: Opaque
stringData:
  hotel-frontend-spgr: http://hotel-frontend-spgr.default.10.125.188.36.sslip.io
  hotel-recommend-partial: http://hotel-recommend-partial.default.10.125.188.36.sslip.io
  hotel-reserve-partial: http://hotel-reserve-partial.default.10.125.188.36.sslip.io
  hotel-user-partial: http://hotel-user-partial.default.10.125.188.36.sslip.io
  hotel-app-database: http://hotel-app-database.default.10.125.188.36.sslip.io
  hotel-app-memcached: http://hotel-app-mmc.default.10.125.188.36.sslip.io
