apiVersion: v1
kind: Service
metadata:
  name: macropod-python
spec:
  selector:
    app: macropod-python
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  clusterIP: 10.43.190.5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macropod-python
spec:
  selector:
    matchLabels:
      app: macropod-python
  replicas: 1
  template:
    metadata:
      labels:
        app: macropod-python
    spec:
      nodeSelector:
        kubernetes.io/hostname: earnest-vm-3
      volumes:
      - name: macropod-pv
        emptyDir:
          medium: Memory
      containers:
      - name: macropod-python-1
        image: arearnest7/macropod-python:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "HTTP"
          - name: FUNC_PORT
            value: "5000"
          - name: GRPC_THREAD
            value: "10"
          - name: RPC_DEST_PV
            value: "/macropod-pv"
          - name: TEST
            value: "127.0.0.1:5001"
          - name: LOGGING_NAME
            value: macropod-python-1
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
      - name: macropod-python-2
        image: arearnest7/macropod-python:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: macropod-pv
          mountPath: /macropod-pv
        env:
          - name: SERVICE_TYPE
            value: "GRPC"
          - name: FUNC_PORT
            value: "5001"
          - name: GRPC_THREAD
            value: "10"
          - name: APP_PV
            value: "/macropod-pv"
          - name: TEST
            value: "127.0.0.1:5001"
          - name: LOGGING_NAME
            value: macropod-python-2
          - name: LOGGING_URL
            value: redis://127.0.0.1
          - name: LOGGING_PASSWORD
            value: password
